#数据源
spring:
  datasource:
    username: dhz
    password: dhzdhzdhz
    url: jdbc:mysql://123.56.145.79:3306/buaase2020dhz?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
      port:6379
      host:182.92.223.226
  mail:
    protocol: smtps
    host: smtp.126.com
    username: notdecidedyet@126.com
    password: OGRFFURPYTUANFDF
    spring.mail.smtp.ssl.enable: true
    port: 465
mybatis:
  mapper-locations: classpath:Mapper/*.xml
# 网络设置
server:
  port:8086
