#数据源
spring:
  datasource:
    username: root
    password: buaase2020.
    url: jdbc:mysql://123.56.145.79:3306/buaase2020?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
      port:6379
      host:182.92.223.226
  mail:
    protocol: smtps
    host: smtp.126.com
    username: notdecidedyet@126.com
    password: OGRFFURPYTUANFDF
    spring.mail.smtp.ssl.enable: true
    port: 465
  http:
    multipart:
      enabled: true
      maxFileSize: 30MB

mybatis:
  mapper-locations: classpath:Mapper/*.xml
# 网络设置
server:
  port: 8086
  maxHttpHeaderSize: 1048576

files:
  path: D:/Files/
  host: localhost:8086
