package cn.edu.buaa.scholarshipserver.dao;

import cn.edu.buaa.scholarshipserver.models.Institution;
import cn.edu.buaa.scholarshipserver.models.InstitutionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InstitutionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Institution
     *
     * @mbggenerated
     */
    int countByExample(InstitutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Institution
     *
     * @mbggenerated
     */
    int deleteByExample(InstitutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Institution
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer institutionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Institution
     *
     * @mbggenerated
     */
    int insert(Institution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Institution
     *
     * @mbggenerated
     */
    int insertSelective(Institution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Institution
     *
     * @mbggenerated
     */
    List<Institution> selectByExample(InstitutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Institution
     *
     * @mbggenerated
     */
    Institution selectByPrimaryKey(Integer institutionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Institution
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Institution record, @Param("example") InstitutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Institution
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Institution record, @Param("example") InstitutionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Institution
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Institution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Institution
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Institution record);
}