package cn.edu.buaa.scholarshipserver.dao;

import cn.edu.buaa.scholarshipserver.models.Paper;
import cn.edu.buaa.scholarshipserver.models.PaperExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Paper
     *
     * @mbggenerated
     */
    int countByExample(PaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Paper
     *
     * @mbggenerated
     */
    int deleteByExample(PaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Paper
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long paperid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Paper
     *
     * @mbggenerated
     */
    int insert(Paper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Paper
     *
     * @mbggenerated
     */
    int insertSelective(Paper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Paper
     *
     * @mbggenerated
     */
    List<Paper> selectByExample(PaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Paper
     *
     * @mbggenerated
     */
    Paper selectByPrimaryKey(Long paperid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Paper
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Paper record, @Param("example") PaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Paper
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Paper record, @Param("example") PaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Paper
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Paper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Paper
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Paper record);
}