package cn.edu.buaa.scholarshipserver.dao;

import cn.edu.buaa.scholarshipserver.models.Patent;
import cn.edu.buaa.scholarshipserver.models.PatentExample;

import java.util.HashMap;
import java.util.List;

import cn.edu.buaa.scholarshipserver.models.Scholar;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface PatentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    int countByExample(PatentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    int deleteByExample(PatentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long patentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    int insert(Patent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    int insertSelective(Patent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    List<Patent> selectByExample(PatentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    Patent selectByPrimaryKey(Long patentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Patent record, @Param("example") PatentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Patent record, @Param("example") PatentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Patent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Patent record);

    Scholar getScholarByUserId(int UID);

    List<HashMap<String, Object>> countOfPatentPossess(int scholarId, int patentId);

    List<HashMap<String, Object>> maxSequenceNumber(int patentId);

    void addPatentPossess(HashMap<String, Object> map);
}