package cn.edu.buaa.scholarshipserver.dao;

import cn.edu.buaa.scholarshipserver.models.Patent;
import cn.edu.buaa.scholarshipserver.models.PatentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PatentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    int countByExample(PatentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    int deleteByExample(PatentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long patentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    int insert(Patent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    int insertSelective(Patent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    List<Patent> selectByExample(PatentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    Patent selectByPrimaryKey(Long patentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Patent record, @Param("example") PatentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Patent record, @Param("example") PatentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Patent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Patent record);
}