package cn.edu.buaa.scholarshipserver.models;

import java.io.Serializable;
import java.util.Date;

public class Fields implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fields.FieldsId
     *
     * @mbggenerated
     */
    private Long fieldsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fields.RankNumber
     *
     * @mbggenerated
     */
    private String ranknumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fields.NormalizedName
     *
     * @mbggenerated
     */
    private String normalizedname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fields.DisplayName
     *
     * @mbggenerated
     */
    private String displayname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fields.MainType
     *
     * @mbggenerated
     */
    private String maintype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fields.Level
     *
     * @mbggenerated
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fields.PaperCount
     *
     * @mbggenerated
     */
    private Long papercount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fields.PaperFamilyCount
     *
     * @mbggenerated
     */
    private Long paperfamilycount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fields.CitationCount
     *
     * @mbggenerated
     */
    private Long citationcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Fields.CreateDate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Fields
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fields.FieldsId
     *
     * @return the value of Fields.FieldsId
     *
     * @mbggenerated
     */
    public Long getFieldsid() {
        return fieldsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fields.FieldsId
     *
     * @param fieldsid the value for Fields.FieldsId
     *
     * @mbggenerated
     */
    public void setFieldsid(Long fieldsid) {
        this.fieldsid = fieldsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fields.RankNumber
     *
     * @return the value of Fields.RankNumber
     *
     * @mbggenerated
     */
    public String getRanknumber() {
        return ranknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fields.RankNumber
     *
     * @param ranknumber the value for Fields.RankNumber
     *
     * @mbggenerated
     */
    public void setRanknumber(String ranknumber) {
        this.ranknumber = ranknumber == null ? null : ranknumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fields.NormalizedName
     *
     * @return the value of Fields.NormalizedName
     *
     * @mbggenerated
     */
    public String getNormalizedname() {
        return normalizedname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fields.NormalizedName
     *
     * @param normalizedname the value for Fields.NormalizedName
     *
     * @mbggenerated
     */
    public void setNormalizedname(String normalizedname) {
        this.normalizedname = normalizedname == null ? null : normalizedname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fields.DisplayName
     *
     * @return the value of Fields.DisplayName
     *
     * @mbggenerated
     */
    public String getDisplayname() {
        return displayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fields.DisplayName
     *
     * @param displayname the value for Fields.DisplayName
     *
     * @mbggenerated
     */
    public void setDisplayname(String displayname) {
        this.displayname = displayname == null ? null : displayname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fields.MainType
     *
     * @return the value of Fields.MainType
     *
     * @mbggenerated
     */
    public String getMaintype() {
        return maintype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fields.MainType
     *
     * @param maintype the value for Fields.MainType
     *
     * @mbggenerated
     */
    public void setMaintype(String maintype) {
        this.maintype = maintype == null ? null : maintype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fields.Level
     *
     * @return the value of Fields.Level
     *
     * @mbggenerated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fields.Level
     *
     * @param level the value for Fields.Level
     *
     * @mbggenerated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fields.PaperCount
     *
     * @return the value of Fields.PaperCount
     *
     * @mbggenerated
     */
    public Long getPapercount() {
        return papercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fields.PaperCount
     *
     * @param papercount the value for Fields.PaperCount
     *
     * @mbggenerated
     */
    public void setPapercount(Long papercount) {
        this.papercount = papercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fields.PaperFamilyCount
     *
     * @return the value of Fields.PaperFamilyCount
     *
     * @mbggenerated
     */
    public Long getPaperfamilycount() {
        return paperfamilycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fields.PaperFamilyCount
     *
     * @param paperfamilycount the value for Fields.PaperFamilyCount
     *
     * @mbggenerated
     */
    public void setPaperfamilycount(Long paperfamilycount) {
        this.paperfamilycount = paperfamilycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fields.CitationCount
     *
     * @return the value of Fields.CitationCount
     *
     * @mbggenerated
     */
    public Long getCitationcount() {
        return citationcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fields.CitationCount
     *
     * @param citationcount the value for Fields.CitationCount
     *
     * @mbggenerated
     */
    public void setCitationcount(Long citationcount) {
        this.citationcount = citationcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Fields.CreateDate
     *
     * @return the value of Fields.CreateDate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Fields.CreateDate
     *
     * @param createdate the value for Fields.CreateDate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Fields
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fieldsid=").append(fieldsid);
        sb.append(", ranknumber=").append(ranknumber);
        sb.append(", normalizedname=").append(normalizedname);
        sb.append(", displayname=").append(displayname);
        sb.append(", maintype=").append(maintype);
        sb.append(", level=").append(level);
        sb.append(", papercount=").append(papercount);
        sb.append(", paperfamilycount=").append(paperfamilycount);
        sb.append(", citationcount=").append(citationcount);
        sb.append(", createdate=").append(createdate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}