package cn.edu.buaa.scholarshipserver.models;

import java.io.Serializable;
import java.util.Date;

public class Message implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Message.MsgId
     *
     * @mbggenerated
     */
    private Integer msgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Message.PaperId
     *
     * @mbggenerated
     */
    private Long paperid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Message.PatentId
     *
     * @mbggenerated
     */
    private Long patentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Message.ProjectId
     *
     * @mbggenerated
     */
    private Long projectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Message.UserID
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Message.Use_UserID
     *
     * @mbggenerated
     */
    private Integer useUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Message.MsgTitle
     *
     * @mbggenerated
     */
    private String msgtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Message.MsgContent
     *
     * @mbggenerated
     */
    private String msgcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Message.MsgStatus
     *
     * @mbggenerated
     */
    private Integer msgstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Message.SendTime
     *
     * @mbggenerated
     */
    private Date sendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Message.MsgType
     *
     * @mbggenerated
     */
    private Integer msgtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Message
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Message.MsgId
     *
     * @return the value of Message.MsgId
     *
     * @mbggenerated
     */
    public Integer getMsgid() {
        return msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Message.MsgId
     *
     * @param msgid the value for Message.MsgId
     *
     * @mbggenerated
     */
    public void setMsgid(Integer msgid) {
        this.msgid = msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Message.PaperId
     *
     * @return the value of Message.PaperId
     *
     * @mbggenerated
     */
    public Long getPaperid() {
        return paperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Message.PaperId
     *
     * @param paperid the value for Message.PaperId
     *
     * @mbggenerated
     */
    public void setPaperid(Long paperid) {
        this.paperid = paperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Message.PatentId
     *
     * @return the value of Message.PatentId
     *
     * @mbggenerated
     */
    public Long getPatentid() {
        return patentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Message.PatentId
     *
     * @param patentid the value for Message.PatentId
     *
     * @mbggenerated
     */
    public void setPatentid(Long patentid) {
        this.patentid = patentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Message.ProjectId
     *
     * @return the value of Message.ProjectId
     *
     * @mbggenerated
     */
    public Long getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Message.ProjectId
     *
     * @param projectid the value for Message.ProjectId
     *
     * @mbggenerated
     */
    public void setProjectid(Long projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Message.UserID
     *
     * @return the value of Message.UserID
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Message.UserID
     *
     * @param userid the value for Message.UserID
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Message.Use_UserID
     *
     * @return the value of Message.Use_UserID
     *
     * @mbggenerated
     */
    public Integer getUseUserid() {
        return useUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Message.Use_UserID
     *
     * @param useUserid the value for Message.Use_UserID
     *
     * @mbggenerated
     */
    public void setUseUserid(Integer useUserid) {
        this.useUserid = useUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Message.MsgTitle
     *
     * @return the value of Message.MsgTitle
     *
     * @mbggenerated
     */
    public String getMsgtitle() {
        return msgtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Message.MsgTitle
     *
     * @param msgtitle the value for Message.MsgTitle
     *
     * @mbggenerated
     */
    public void setMsgtitle(String msgtitle) {
        this.msgtitle = msgtitle == null ? null : msgtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Message.MsgContent
     *
     * @return the value of Message.MsgContent
     *
     * @mbggenerated
     */
    public String getMsgcontent() {
        return msgcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Message.MsgContent
     *
     * @param msgcontent the value for Message.MsgContent
     *
     * @mbggenerated
     */
    public void setMsgcontent(String msgcontent) {
        this.msgcontent = msgcontent == null ? null : msgcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Message.MsgStatus
     *
     * @return the value of Message.MsgStatus
     *
     * @mbggenerated
     */
    public Integer getMsgstatus() {
        return msgstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Message.MsgStatus
     *
     * @param msgstatus the value for Message.MsgStatus
     *
     * @mbggenerated
     */
    public void setMsgstatus(Integer msgstatus) {
        this.msgstatus = msgstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Message.SendTime
     *
     * @return the value of Message.SendTime
     *
     * @mbggenerated
     */
    public Date getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Message.SendTime
     *
     * @param sendtime the value for Message.SendTime
     *
     * @mbggenerated
     */
    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Message.MsgType
     *
     * @return the value of Message.MsgType
     *
     * @mbggenerated
     */
    public Integer getMsgtype() {
        return msgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Message.MsgType
     *
     * @param msgtype the value for Message.MsgType
     *
     * @mbggenerated
     */
    public void setMsgtype(Integer msgtype) {
        this.msgtype = msgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Message
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", msgid=").append(msgid);
        sb.append(", paperid=").append(paperid);
        sb.append(", patentid=").append(patentid);
        sb.append(", projectid=").append(projectid);
        sb.append(", userid=").append(userid);
        sb.append(", useUserid=").append(useUserid);
        sb.append(", msgtitle=").append(msgtitle);
        sb.append(", msgcontent=").append(msgcontent);
        sb.append(", msgstatus=").append(msgstatus);
        sb.append(", sendtime=").append(sendtime);
        sb.append(", msgtype=").append(msgtype);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}