package cn.edu.buaa.scholarshipserver.models;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class PaperExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Paper
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Paper
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Paper
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Paper
     *
     * @mbggenerated
     */
    public PaperExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Paper
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Paper
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Paper
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Paper
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Paper
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Paper
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Paper
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Paper
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Paper
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Paper
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Paper
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andPaperidIsNull() {
            addCriterion("PaperId is null");
            return (Criteria) this;
        }

        public Criteria andPaperidIsNotNull() {
            addCriterion("PaperId is not null");
            return (Criteria) this;
        }

        public Criteria andPaperidEqualTo(Long value) {
            addCriterion("PaperId =", value, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidNotEqualTo(Long value) {
            addCriterion("PaperId <>", value, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidGreaterThan(Long value) {
            addCriterion("PaperId >", value, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidGreaterThanOrEqualTo(Long value) {
            addCriterion("PaperId >=", value, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidLessThan(Long value) {
            addCriterion("PaperId <", value, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidLessThanOrEqualTo(Long value) {
            addCriterion("PaperId <=", value, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidIn(List<Long> values) {
            addCriterion("PaperId in", values, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidNotIn(List<Long> values) {
            addCriterion("PaperId not in", values, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidBetween(Long value1, Long value2) {
            addCriterion("PaperId between", value1, value2, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidNotBetween(Long value1, Long value2) {
            addCriterion("PaperId not between", value1, value2, "paperid");
            return (Criteria) this;
        }

        public Criteria andDoiIsNull() {
            addCriterion("Doi is null");
            return (Criteria) this;
        }

        public Criteria andDoiIsNotNull() {
            addCriterion("Doi is not null");
            return (Criteria) this;
        }

        public Criteria andDoiEqualTo(String value) {
            addCriterion("Doi =", value, "doi");
            return (Criteria) this;
        }

        public Criteria andDoiNotEqualTo(String value) {
            addCriterion("Doi <>", value, "doi");
            return (Criteria) this;
        }

        public Criteria andDoiGreaterThan(String value) {
            addCriterion("Doi >", value, "doi");
            return (Criteria) this;
        }

        public Criteria andDoiGreaterThanOrEqualTo(String value) {
            addCriterion("Doi >=", value, "doi");
            return (Criteria) this;
        }

        public Criteria andDoiLessThan(String value) {
            addCriterion("Doi <", value, "doi");
            return (Criteria) this;
        }

        public Criteria andDoiLessThanOrEqualTo(String value) {
            addCriterion("Doi <=", value, "doi");
            return (Criteria) this;
        }

        public Criteria andDoiLike(String value) {
            addCriterion("Doi like", value, "doi");
            return (Criteria) this;
        }

        public Criteria andDoiNotLike(String value) {
            addCriterion("Doi not like", value, "doi");
            return (Criteria) this;
        }

        public Criteria andDoiIn(List<String> values) {
            addCriterion("Doi in", values, "doi");
            return (Criteria) this;
        }

        public Criteria andDoiNotIn(List<String> values) {
            addCriterion("Doi not in", values, "doi");
            return (Criteria) this;
        }

        public Criteria andDoiBetween(String value1, String value2) {
            addCriterion("Doi between", value1, value2, "doi");
            return (Criteria) this;
        }

        public Criteria andDoiNotBetween(String value1, String value2) {
            addCriterion("Doi not between", value1, value2, "doi");
            return (Criteria) this;
        }

        public Criteria andDoctypeIsNull() {
            addCriterion("DocType is null");
            return (Criteria) this;
        }

        public Criteria andDoctypeIsNotNull() {
            addCriterion("DocType is not null");
            return (Criteria) this;
        }

        public Criteria andDoctypeEqualTo(String value) {
            addCriterion("DocType =", value, "doctype");
            return (Criteria) this;
        }

        public Criteria andDoctypeNotEqualTo(String value) {
            addCriterion("DocType <>", value, "doctype");
            return (Criteria) this;
        }

        public Criteria andDoctypeGreaterThan(String value) {
            addCriterion("DocType >", value, "doctype");
            return (Criteria) this;
        }

        public Criteria andDoctypeGreaterThanOrEqualTo(String value) {
            addCriterion("DocType >=", value, "doctype");
            return (Criteria) this;
        }

        public Criteria andDoctypeLessThan(String value) {
            addCriterion("DocType <", value, "doctype");
            return (Criteria) this;
        }

        public Criteria andDoctypeLessThanOrEqualTo(String value) {
            addCriterion("DocType <=", value, "doctype");
            return (Criteria) this;
        }

        public Criteria andDoctypeLike(String value) {
            addCriterion("DocType like", value, "doctype");
            return (Criteria) this;
        }

        public Criteria andDoctypeNotLike(String value) {
            addCriterion("DocType not like", value, "doctype");
            return (Criteria) this;
        }

        public Criteria andDoctypeIn(List<String> values) {
            addCriterion("DocType in", values, "doctype");
            return (Criteria) this;
        }

        public Criteria andDoctypeNotIn(List<String> values) {
            addCriterion("DocType not in", values, "doctype");
            return (Criteria) this;
        }

        public Criteria andDoctypeBetween(String value1, String value2) {
            addCriterion("DocType between", value1, value2, "doctype");
            return (Criteria) this;
        }

        public Criteria andDoctypeNotBetween(String value1, String value2) {
            addCriterion("DocType not between", value1, value2, "doctype");
            return (Criteria) this;
        }

        public Criteria andPapertitleIsNull() {
            addCriterion("PaperTitle is null");
            return (Criteria) this;
        }

        public Criteria andPapertitleIsNotNull() {
            addCriterion("PaperTitle is not null");
            return (Criteria) this;
        }

        public Criteria andPapertitleEqualTo(String value) {
            addCriterion("PaperTitle =", value, "papertitle");
            return (Criteria) this;
        }

        public Criteria andPapertitleNotEqualTo(String value) {
            addCriterion("PaperTitle <>", value, "papertitle");
            return (Criteria) this;
        }

        public Criteria andPapertitleGreaterThan(String value) {
            addCriterion("PaperTitle >", value, "papertitle");
            return (Criteria) this;
        }

        public Criteria andPapertitleGreaterThanOrEqualTo(String value) {
            addCriterion("PaperTitle >=", value, "papertitle");
            return (Criteria) this;
        }

        public Criteria andPapertitleLessThan(String value) {
            addCriterion("PaperTitle <", value, "papertitle");
            return (Criteria) this;
        }

        public Criteria andPapertitleLessThanOrEqualTo(String value) {
            addCriterion("PaperTitle <=", value, "papertitle");
            return (Criteria) this;
        }

        public Criteria andPapertitleLike(String value) {
            addCriterion("PaperTitle like", value, "papertitle");
            return (Criteria) this;
        }

        public Criteria andPapertitleNotLike(String value) {
            addCriterion("PaperTitle not like", value, "papertitle");
            return (Criteria) this;
        }

        public Criteria andPapertitleIn(List<String> values) {
            addCriterion("PaperTitle in", values, "papertitle");
            return (Criteria) this;
        }

        public Criteria andPapertitleNotIn(List<String> values) {
            addCriterion("PaperTitle not in", values, "papertitle");
            return (Criteria) this;
        }

        public Criteria andPapertitleBetween(String value1, String value2) {
            addCriterion("PaperTitle between", value1, value2, "papertitle");
            return (Criteria) this;
        }

        public Criteria andPapertitleNotBetween(String value1, String value2) {
            addCriterion("PaperTitle not between", value1, value2, "papertitle");
            return (Criteria) this;
        }

        public Criteria andAbtractIsNull() {
            addCriterion("Abtract is null");
            return (Criteria) this;
        }

        public Criteria andAbtractIsNotNull() {
            addCriterion("Abtract is not null");
            return (Criteria) this;
        }

        public Criteria andAbtractEqualTo(String value) {
            addCriterion("Abtract =", value, "abtract");
            return (Criteria) this;
        }

        public Criteria andAbtractNotEqualTo(String value) {
            addCriterion("Abtract <>", value, "abtract");
            return (Criteria) this;
        }

        public Criteria andAbtractGreaterThan(String value) {
            addCriterion("Abtract >", value, "abtract");
            return (Criteria) this;
        }

        public Criteria andAbtractGreaterThanOrEqualTo(String value) {
            addCriterion("Abtract >=", value, "abtract");
            return (Criteria) this;
        }

        public Criteria andAbtractLessThan(String value) {
            addCriterion("Abtract <", value, "abtract");
            return (Criteria) this;
        }

        public Criteria andAbtractLessThanOrEqualTo(String value) {
            addCriterion("Abtract <=", value, "abtract");
            return (Criteria) this;
        }

        public Criteria andAbtractLike(String value) {
            addCriterion("Abtract like", value, "abtract");
            return (Criteria) this;
        }

        public Criteria andAbtractNotLike(String value) {
            addCriterion("Abtract not like", value, "abtract");
            return (Criteria) this;
        }

        public Criteria andAbtractIn(List<String> values) {
            addCriterion("Abtract in", values, "abtract");
            return (Criteria) this;
        }

        public Criteria andAbtractNotIn(List<String> values) {
            addCriterion("Abtract not in", values, "abtract");
            return (Criteria) this;
        }

        public Criteria andAbtractBetween(String value1, String value2) {
            addCriterion("Abtract between", value1, value2, "abtract");
            return (Criteria) this;
        }

        public Criteria andAbtractNotBetween(String value1, String value2) {
            addCriterion("Abtract not between", value1, value2, "abtract");
            return (Criteria) this;
        }

        public Criteria andCitationcountIsNull() {
            addCriterion("CitationCount is null");
            return (Criteria) this;
        }

        public Criteria andCitationcountIsNotNull() {
            addCriterion("CitationCount is not null");
            return (Criteria) this;
        }

        public Criteria andCitationcountEqualTo(Long value) {
            addCriterion("CitationCount =", value, "citationcount");
            return (Criteria) this;
        }

        public Criteria andCitationcountNotEqualTo(Long value) {
            addCriterion("CitationCount <>", value, "citationcount");
            return (Criteria) this;
        }

        public Criteria andCitationcountGreaterThan(Long value) {
            addCriterion("CitationCount >", value, "citationcount");
            return (Criteria) this;
        }

        public Criteria andCitationcountGreaterThanOrEqualTo(Long value) {
            addCriterion("CitationCount >=", value, "citationcount");
            return (Criteria) this;
        }

        public Criteria andCitationcountLessThan(Long value) {
            addCriterion("CitationCount <", value, "citationcount");
            return (Criteria) this;
        }

        public Criteria andCitationcountLessThanOrEqualTo(Long value) {
            addCriterion("CitationCount <=", value, "citationcount");
            return (Criteria) this;
        }

        public Criteria andCitationcountIn(List<Long> values) {
            addCriterion("CitationCount in", values, "citationcount");
            return (Criteria) this;
        }

        public Criteria andCitationcountNotIn(List<Long> values) {
            addCriterion("CitationCount not in", values, "citationcount");
            return (Criteria) this;
        }

        public Criteria andCitationcountBetween(Long value1, Long value2) {
            addCriterion("CitationCount between", value1, value2, "citationcount");
            return (Criteria) this;
        }

        public Criteria andCitationcountNotBetween(Long value1, Long value2) {
            addCriterion("CitationCount not between", value1, value2, "citationcount");
            return (Criteria) this;
        }

        public Criteria andDateIsNull() {
            addCriterion("Date is null");
            return (Criteria) this;
        }

        public Criteria andDateIsNotNull() {
            addCriterion("Date is not null");
            return (Criteria) this;
        }

        public Criteria andDateEqualTo(Date value) {
            addCriterionForJDBCDate("Date =", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("Date <>", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThan(Date value) {
            addCriterionForJDBCDate("Date >", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("Date >=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThan(Date value) {
            addCriterionForJDBCDate("Date <", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("Date <=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateIn(List<Date> values) {
            addCriterionForJDBCDate("Date in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("Date not in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("Date between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("Date not between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andJournalIsNull() {
            addCriterion("Journal is null");
            return (Criteria) this;
        }

        public Criteria andJournalIsNotNull() {
            addCriterion("Journal is not null");
            return (Criteria) this;
        }

        public Criteria andJournalEqualTo(String value) {
            addCriterion("Journal =", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalNotEqualTo(String value) {
            addCriterion("Journal <>", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalGreaterThan(String value) {
            addCriterion("Journal >", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalGreaterThanOrEqualTo(String value) {
            addCriterion("Journal >=", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalLessThan(String value) {
            addCriterion("Journal <", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalLessThanOrEqualTo(String value) {
            addCriterion("Journal <=", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalLike(String value) {
            addCriterion("Journal like", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalNotLike(String value) {
            addCriterion("Journal not like", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalIn(List<String> values) {
            addCriterion("Journal in", values, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalNotIn(List<String> values) {
            addCriterion("Journal not in", values, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalBetween(String value1, String value2) {
            addCriterion("Journal between", value1, value2, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalNotBetween(String value1, String value2) {
            addCriterion("Journal not between", value1, value2, "journal");
            return (Criteria) this;
        }

        public Criteria andConferenceIsNull() {
            addCriterion("Conference is null");
            return (Criteria) this;
        }

        public Criteria andConferenceIsNotNull() {
            addCriterion("Conference is not null");
            return (Criteria) this;
        }

        public Criteria andConferenceEqualTo(String value) {
            addCriterion("Conference =", value, "conference");
            return (Criteria) this;
        }

        public Criteria andConferenceNotEqualTo(String value) {
            addCriterion("Conference <>", value, "conference");
            return (Criteria) this;
        }

        public Criteria andConferenceGreaterThan(String value) {
            addCriterion("Conference >", value, "conference");
            return (Criteria) this;
        }

        public Criteria andConferenceGreaterThanOrEqualTo(String value) {
            addCriterion("Conference >=", value, "conference");
            return (Criteria) this;
        }

        public Criteria andConferenceLessThan(String value) {
            addCriterion("Conference <", value, "conference");
            return (Criteria) this;
        }

        public Criteria andConferenceLessThanOrEqualTo(String value) {
            addCriterion("Conference <=", value, "conference");
            return (Criteria) this;
        }

        public Criteria andConferenceLike(String value) {
            addCriterion("Conference like", value, "conference");
            return (Criteria) this;
        }

        public Criteria andConferenceNotLike(String value) {
            addCriterion("Conference not like", value, "conference");
            return (Criteria) this;
        }

        public Criteria andConferenceIn(List<String> values) {
            addCriterion("Conference in", values, "conference");
            return (Criteria) this;
        }

        public Criteria andConferenceNotIn(List<String> values) {
            addCriterion("Conference not in", values, "conference");
            return (Criteria) this;
        }

        public Criteria andConferenceBetween(String value1, String value2) {
            addCriterion("Conference between", value1, value2, "conference");
            return (Criteria) this;
        }

        public Criteria andConferenceNotBetween(String value1, String value2) {
            addCriterion("Conference not between", value1, value2, "conference");
            return (Criteria) this;
        }

        public Criteria andVolumeIsNull() {
            addCriterion("Volume is null");
            return (Criteria) this;
        }

        public Criteria andVolumeIsNotNull() {
            addCriterion("Volume is not null");
            return (Criteria) this;
        }

        public Criteria andVolumeEqualTo(String value) {
            addCriterion("Volume =", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeNotEqualTo(String value) {
            addCriterion("Volume <>", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeGreaterThan(String value) {
            addCriterion("Volume >", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeGreaterThanOrEqualTo(String value) {
            addCriterion("Volume >=", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeLessThan(String value) {
            addCriterion("Volume <", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeLessThanOrEqualTo(String value) {
            addCriterion("Volume <=", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeLike(String value) {
            addCriterion("Volume like", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeNotLike(String value) {
            addCriterion("Volume not like", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeIn(List<String> values) {
            addCriterion("Volume in", values, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeNotIn(List<String> values) {
            addCriterion("Volume not in", values, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeBetween(String value1, String value2) {
            addCriterion("Volume between", value1, value2, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeNotBetween(String value1, String value2) {
            addCriterion("Volume not between", value1, value2, "volume");
            return (Criteria) this;
        }

        public Criteria andIssueIsNull() {
            addCriterion("Issue is null");
            return (Criteria) this;
        }

        public Criteria andIssueIsNotNull() {
            addCriterion("Issue is not null");
            return (Criteria) this;
        }

        public Criteria andIssueEqualTo(String value) {
            addCriterion("Issue =", value, "issue");
            return (Criteria) this;
        }

        public Criteria andIssueNotEqualTo(String value) {
            addCriterion("Issue <>", value, "issue");
            return (Criteria) this;
        }

        public Criteria andIssueGreaterThan(String value) {
            addCriterion("Issue >", value, "issue");
            return (Criteria) this;
        }

        public Criteria andIssueGreaterThanOrEqualTo(String value) {
            addCriterion("Issue >=", value, "issue");
            return (Criteria) this;
        }

        public Criteria andIssueLessThan(String value) {
            addCriterion("Issue <", value, "issue");
            return (Criteria) this;
        }

        public Criteria andIssueLessThanOrEqualTo(String value) {
            addCriterion("Issue <=", value, "issue");
            return (Criteria) this;
        }

        public Criteria andIssueLike(String value) {
            addCriterion("Issue like", value, "issue");
            return (Criteria) this;
        }

        public Criteria andIssueNotLike(String value) {
            addCriterion("Issue not like", value, "issue");
            return (Criteria) this;
        }

        public Criteria andIssueIn(List<String> values) {
            addCriterion("Issue in", values, "issue");
            return (Criteria) this;
        }

        public Criteria andIssueNotIn(List<String> values) {
            addCriterion("Issue not in", values, "issue");
            return (Criteria) this;
        }

        public Criteria andIssueBetween(String value1, String value2) {
            addCriterion("Issue between", value1, value2, "issue");
            return (Criteria) this;
        }

        public Criteria andIssueNotBetween(String value1, String value2) {
            addCriterion("Issue not between", value1, value2, "issue");
            return (Criteria) this;
        }

        public Criteria andFirstpageIsNull() {
            addCriterion("FirstPage is null");
            return (Criteria) this;
        }

        public Criteria andFirstpageIsNotNull() {
            addCriterion("FirstPage is not null");
            return (Criteria) this;
        }

        public Criteria andFirstpageEqualTo(String value) {
            addCriterion("FirstPage =", value, "firstpage");
            return (Criteria) this;
        }

        public Criteria andFirstpageNotEqualTo(String value) {
            addCriterion("FirstPage <>", value, "firstpage");
            return (Criteria) this;
        }

        public Criteria andFirstpageGreaterThan(String value) {
            addCriterion("FirstPage >", value, "firstpage");
            return (Criteria) this;
        }

        public Criteria andFirstpageGreaterThanOrEqualTo(String value) {
            addCriterion("FirstPage >=", value, "firstpage");
            return (Criteria) this;
        }

        public Criteria andFirstpageLessThan(String value) {
            addCriterion("FirstPage <", value, "firstpage");
            return (Criteria) this;
        }

        public Criteria andFirstpageLessThanOrEqualTo(String value) {
            addCriterion("FirstPage <=", value, "firstpage");
            return (Criteria) this;
        }

        public Criteria andFirstpageLike(String value) {
            addCriterion("FirstPage like", value, "firstpage");
            return (Criteria) this;
        }

        public Criteria andFirstpageNotLike(String value) {
            addCriterion("FirstPage not like", value, "firstpage");
            return (Criteria) this;
        }

        public Criteria andFirstpageIn(List<String> values) {
            addCriterion("FirstPage in", values, "firstpage");
            return (Criteria) this;
        }

        public Criteria andFirstpageNotIn(List<String> values) {
            addCriterion("FirstPage not in", values, "firstpage");
            return (Criteria) this;
        }

        public Criteria andFirstpageBetween(String value1, String value2) {
            addCriterion("FirstPage between", value1, value2, "firstpage");
            return (Criteria) this;
        }

        public Criteria andFirstpageNotBetween(String value1, String value2) {
            addCriterion("FirstPage not between", value1, value2, "firstpage");
            return (Criteria) this;
        }

        public Criteria andLastpageIsNull() {
            addCriterion("LastPage is null");
            return (Criteria) this;
        }

        public Criteria andLastpageIsNotNull() {
            addCriterion("LastPage is not null");
            return (Criteria) this;
        }

        public Criteria andLastpageEqualTo(String value) {
            addCriterion("LastPage =", value, "lastpage");
            return (Criteria) this;
        }

        public Criteria andLastpageNotEqualTo(String value) {
            addCriterion("LastPage <>", value, "lastpage");
            return (Criteria) this;
        }

        public Criteria andLastpageGreaterThan(String value) {
            addCriterion("LastPage >", value, "lastpage");
            return (Criteria) this;
        }

        public Criteria andLastpageGreaterThanOrEqualTo(String value) {
            addCriterion("LastPage >=", value, "lastpage");
            return (Criteria) this;
        }

        public Criteria andLastpageLessThan(String value) {
            addCriterion("LastPage <", value, "lastpage");
            return (Criteria) this;
        }

        public Criteria andLastpageLessThanOrEqualTo(String value) {
            addCriterion("LastPage <=", value, "lastpage");
            return (Criteria) this;
        }

        public Criteria andLastpageLike(String value) {
            addCriterion("LastPage like", value, "lastpage");
            return (Criteria) this;
        }

        public Criteria andLastpageNotLike(String value) {
            addCriterion("LastPage not like", value, "lastpage");
            return (Criteria) this;
        }

        public Criteria andLastpageIn(List<String> values) {
            addCriterion("LastPage in", values, "lastpage");
            return (Criteria) this;
        }

        public Criteria andLastpageNotIn(List<String> values) {
            addCriterion("LastPage not in", values, "lastpage");
            return (Criteria) this;
        }

        public Criteria andLastpageBetween(String value1, String value2) {
            addCriterion("LastPage between", value1, value2, "lastpage");
            return (Criteria) this;
        }

        public Criteria andLastpageNotBetween(String value1, String value2) {
            addCriterion("LastPage not between", value1, value2, "lastpage");
            return (Criteria) this;
        }

        public Criteria andSourceurlIsNull() {
            addCriterion("SourceUrl is null");
            return (Criteria) this;
        }

        public Criteria andSourceurlIsNotNull() {
            addCriterion("SourceUrl is not null");
            return (Criteria) this;
        }

        public Criteria andSourceurlEqualTo(String value) {
            addCriterion("SourceUrl =", value, "sourceurl");
            return (Criteria) this;
        }

        public Criteria andSourceurlNotEqualTo(String value) {
            addCriterion("SourceUrl <>", value, "sourceurl");
            return (Criteria) this;
        }

        public Criteria andSourceurlGreaterThan(String value) {
            addCriterion("SourceUrl >", value, "sourceurl");
            return (Criteria) this;
        }

        public Criteria andSourceurlGreaterThanOrEqualTo(String value) {
            addCriterion("SourceUrl >=", value, "sourceurl");
            return (Criteria) this;
        }

        public Criteria andSourceurlLessThan(String value) {
            addCriterion("SourceUrl <", value, "sourceurl");
            return (Criteria) this;
        }

        public Criteria andSourceurlLessThanOrEqualTo(String value) {
            addCriterion("SourceUrl <=", value, "sourceurl");
            return (Criteria) this;
        }

        public Criteria andSourceurlLike(String value) {
            addCriterion("SourceUrl like", value, "sourceurl");
            return (Criteria) this;
        }

        public Criteria andSourceurlNotLike(String value) {
            addCriterion("SourceUrl not like", value, "sourceurl");
            return (Criteria) this;
        }

        public Criteria andSourceurlIn(List<String> values) {
            addCriterion("SourceUrl in", values, "sourceurl");
            return (Criteria) this;
        }

        public Criteria andSourceurlNotIn(List<String> values) {
            addCriterion("SourceUrl not in", values, "sourceurl");
            return (Criteria) this;
        }

        public Criteria andSourceurlBetween(String value1, String value2) {
            addCriterion("SourceUrl between", value1, value2, "sourceurl");
            return (Criteria) this;
        }

        public Criteria andSourceurlNotBetween(String value1, String value2) {
            addCriterion("SourceUrl not between", value1, value2, "sourceurl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Paper
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Paper
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}