package cn.edu.buaa.scholarshipserver.models;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class PatentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Patent
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Patent
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Patent
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    public PatentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Patent
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Patent
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andPatentidIsNull() {
            addCriterion("PatentId is null");
            return (Criteria) this;
        }

        public Criteria andPatentidIsNotNull() {
            addCriterion("PatentId is not null");
            return (Criteria) this;
        }

        public Criteria andPatentidEqualTo(Long value) {
            addCriterion("PatentId =", value, "patentid");
            return (Criteria) this;
        }

        public Criteria andPatentidNotEqualTo(Long value) {
            addCriterion("PatentId <>", value, "patentid");
            return (Criteria) this;
        }

        public Criteria andPatentidGreaterThan(Long value) {
            addCriterion("PatentId >", value, "patentid");
            return (Criteria) this;
        }

        public Criteria andPatentidGreaterThanOrEqualTo(Long value) {
            addCriterion("PatentId >=", value, "patentid");
            return (Criteria) this;
        }

        public Criteria andPatentidLessThan(Long value) {
            addCriterion("PatentId <", value, "patentid");
            return (Criteria) this;
        }

        public Criteria andPatentidLessThanOrEqualTo(Long value) {
            addCriterion("PatentId <=", value, "patentid");
            return (Criteria) this;
        }

        public Criteria andPatentidIn(List<Long> values) {
            addCriterion("PatentId in", values, "patentid");
            return (Criteria) this;
        }

        public Criteria andPatentidNotIn(List<Long> values) {
            addCriterion("PatentId not in", values, "patentid");
            return (Criteria) this;
        }

        public Criteria andPatentidBetween(Long value1, Long value2) {
            addCriterion("PatentId between", value1, value2, "patentid");
            return (Criteria) this;
        }

        public Criteria andPatentidNotBetween(Long value1, Long value2) {
            addCriterion("PatentId not between", value1, value2, "patentid");
            return (Criteria) this;
        }

        public Criteria andAbtractIsNull() {
            addCriterion("Abtract is null");
            return (Criteria) this;
        }

        public Criteria andAbtractIsNotNull() {
            addCriterion("Abtract is not null");
            return (Criteria) this;
        }

        public Criteria andAbtractEqualTo(String value) {
            addCriterion("Abtract =", value, "abtract");
            return (Criteria) this;
        }

        public Criteria andAbtractNotEqualTo(String value) {
            addCriterion("Abtract <>", value, "abtract");
            return (Criteria) this;
        }

        public Criteria andAbtractGreaterThan(String value) {
            addCriterion("Abtract >", value, "abtract");
            return (Criteria) this;
        }

        public Criteria andAbtractGreaterThanOrEqualTo(String value) {
            addCriterion("Abtract >=", value, "abtract");
            return (Criteria) this;
        }

        public Criteria andAbtractLessThan(String value) {
            addCriterion("Abtract <", value, "abtract");
            return (Criteria) this;
        }

        public Criteria andAbtractLessThanOrEqualTo(String value) {
            addCriterion("Abtract <=", value, "abtract");
            return (Criteria) this;
        }

        public Criteria andAbtractLike(String value) {
            addCriterion("Abtract like", value, "abtract");
            return (Criteria) this;
        }

        public Criteria andAbtractNotLike(String value) {
            addCriterion("Abtract not like", value, "abtract");
            return (Criteria) this;
        }

        public Criteria andAbtractIn(List<String> values) {
            addCriterion("Abtract in", values, "abtract");
            return (Criteria) this;
        }

        public Criteria andAbtractNotIn(List<String> values) {
            addCriterion("Abtract not in", values, "abtract");
            return (Criteria) this;
        }

        public Criteria andAbtractBetween(String value1, String value2) {
            addCriterion("Abtract between", value1, value2, "abtract");
            return (Criteria) this;
        }

        public Criteria andAbtractNotBetween(String value1, String value2) {
            addCriterion("Abtract not between", value1, value2, "abtract");
            return (Criteria) this;
        }

        public Criteria andApplicationdateIsNull() {
            addCriterion("ApplicationDate is null");
            return (Criteria) this;
        }

        public Criteria andApplicationdateIsNotNull() {
            addCriterion("ApplicationDate is not null");
            return (Criteria) this;
        }

        public Criteria andApplicationdateEqualTo(Date value) {
            addCriterionForJDBCDate("ApplicationDate =", value, "applicationdate");
            return (Criteria) this;
        }

        public Criteria andApplicationdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("ApplicationDate <>", value, "applicationdate");
            return (Criteria) this;
        }

        public Criteria andApplicationdateGreaterThan(Date value) {
            addCriterionForJDBCDate("ApplicationDate >", value, "applicationdate");
            return (Criteria) this;
        }

        public Criteria andApplicationdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ApplicationDate >=", value, "applicationdate");
            return (Criteria) this;
        }

        public Criteria andApplicationdateLessThan(Date value) {
            addCriterionForJDBCDate("ApplicationDate <", value, "applicationdate");
            return (Criteria) this;
        }

        public Criteria andApplicationdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ApplicationDate <=", value, "applicationdate");
            return (Criteria) this;
        }

        public Criteria andApplicationdateIn(List<Date> values) {
            addCriterionForJDBCDate("ApplicationDate in", values, "applicationdate");
            return (Criteria) this;
        }

        public Criteria andApplicationdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("ApplicationDate not in", values, "applicationdate");
            return (Criteria) this;
        }

        public Criteria andApplicationdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ApplicationDate between", value1, value2, "applicationdate");
            return (Criteria) this;
        }

        public Criteria andApplicationdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ApplicationDate not between", value1, value2, "applicationdate");
            return (Criteria) this;
        }

        public Criteria andAgencyIsNull() {
            addCriterion("Agency is null");
            return (Criteria) this;
        }

        public Criteria andAgencyIsNotNull() {
            addCriterion("Agency is not null");
            return (Criteria) this;
        }

        public Criteria andAgencyEqualTo(String value) {
            addCriterion("Agency =", value, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyNotEqualTo(String value) {
            addCriterion("Agency <>", value, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyGreaterThan(String value) {
            addCriterion("Agency >", value, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyGreaterThanOrEqualTo(String value) {
            addCriterion("Agency >=", value, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyLessThan(String value) {
            addCriterion("Agency <", value, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyLessThanOrEqualTo(String value) {
            addCriterion("Agency <=", value, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyLike(String value) {
            addCriterion("Agency like", value, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyNotLike(String value) {
            addCriterion("Agency not like", value, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyIn(List<String> values) {
            addCriterion("Agency in", values, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyNotIn(List<String> values) {
            addCriterion("Agency not in", values, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyBetween(String value1, String value2) {
            addCriterion("Agency between", value1, value2, "agency");
            return (Criteria) this;
        }

        public Criteria andAgencyNotBetween(String value1, String value2) {
            addCriterion("Agency not between", value1, value2, "agency");
            return (Criteria) this;
        }

        public Criteria andApplicationnumberIsNull() {
            addCriterion("ApplicationNumber is null");
            return (Criteria) this;
        }

        public Criteria andApplicationnumberIsNotNull() {
            addCriterion("ApplicationNumber is not null");
            return (Criteria) this;
        }

        public Criteria andApplicationnumberEqualTo(String value) {
            addCriterion("ApplicationNumber =", value, "applicationnumber");
            return (Criteria) this;
        }

        public Criteria andApplicationnumberNotEqualTo(String value) {
            addCriterion("ApplicationNumber <>", value, "applicationnumber");
            return (Criteria) this;
        }

        public Criteria andApplicationnumberGreaterThan(String value) {
            addCriterion("ApplicationNumber >", value, "applicationnumber");
            return (Criteria) this;
        }

        public Criteria andApplicationnumberGreaterThanOrEqualTo(String value) {
            addCriterion("ApplicationNumber >=", value, "applicationnumber");
            return (Criteria) this;
        }

        public Criteria andApplicationnumberLessThan(String value) {
            addCriterion("ApplicationNumber <", value, "applicationnumber");
            return (Criteria) this;
        }

        public Criteria andApplicationnumberLessThanOrEqualTo(String value) {
            addCriterion("ApplicationNumber <=", value, "applicationnumber");
            return (Criteria) this;
        }

        public Criteria andApplicationnumberLike(String value) {
            addCriterion("ApplicationNumber like", value, "applicationnumber");
            return (Criteria) this;
        }

        public Criteria andApplicationnumberNotLike(String value) {
            addCriterion("ApplicationNumber not like", value, "applicationnumber");
            return (Criteria) this;
        }

        public Criteria andApplicationnumberIn(List<String> values) {
            addCriterion("ApplicationNumber in", values, "applicationnumber");
            return (Criteria) this;
        }

        public Criteria andApplicationnumberNotIn(List<String> values) {
            addCriterion("ApplicationNumber not in", values, "applicationnumber");
            return (Criteria) this;
        }

        public Criteria andApplicationnumberBetween(String value1, String value2) {
            addCriterion("ApplicationNumber between", value1, value2, "applicationnumber");
            return (Criteria) this;
        }

        public Criteria andApplicationnumberNotBetween(String value1, String value2) {
            addCriterion("ApplicationNumber not between", value1, value2, "applicationnumber");
            return (Criteria) this;
        }

        public Criteria andAgentIsNull() {
            addCriterion("Agent is null");
            return (Criteria) this;
        }

        public Criteria andAgentIsNotNull() {
            addCriterion("Agent is not null");
            return (Criteria) this;
        }

        public Criteria andAgentEqualTo(String value) {
            addCriterion("Agent =", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentNotEqualTo(String value) {
            addCriterion("Agent <>", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentGreaterThan(String value) {
            addCriterion("Agent >", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentGreaterThanOrEqualTo(String value) {
            addCriterion("Agent >=", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentLessThan(String value) {
            addCriterion("Agent <", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentLessThanOrEqualTo(String value) {
            addCriterion("Agent <=", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentLike(String value) {
            addCriterion("Agent like", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentNotLike(String value) {
            addCriterion("Agent not like", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentIn(List<String> values) {
            addCriterion("Agent in", values, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentNotIn(List<String> values) {
            addCriterion("Agent not in", values, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentBetween(String value1, String value2) {
            addCriterion("Agent between", value1, value2, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentNotBetween(String value1, String value2) {
            addCriterion("Agent not between", value1, value2, "agent");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("Content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("Content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("Content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("Content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("Content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("Content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("Content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("Content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("Content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("Content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("Content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("Content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("Content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("Content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("Province is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("Province is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("Province =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("Province <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("Province >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("Province >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("Province <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("Province <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("Province like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("Province not like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<String> values) {
            addCriterion("Province in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<String> values) {
            addCriterion("Province not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("Province between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("Province not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andLocationIsNull() {
            addCriterion("Location is null");
            return (Criteria) this;
        }

        public Criteria andLocationIsNotNull() {
            addCriterion("Location is not null");
            return (Criteria) this;
        }

        public Criteria andLocationEqualTo(String value) {
            addCriterion("Location =", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotEqualTo(String value) {
            addCriterion("Location <>", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThan(String value) {
            addCriterion("Location >", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThanOrEqualTo(String value) {
            addCriterion("Location >=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThan(String value) {
            addCriterion("Location <", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThanOrEqualTo(String value) {
            addCriterion("Location <=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLike(String value) {
            addCriterion("Location like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotLike(String value) {
            addCriterion("Location not like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationIn(List<String> values) {
            addCriterion("Location in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotIn(List<String> values) {
            addCriterion("Location not in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationBetween(String value1, String value2) {
            addCriterion("Location between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotBetween(String value1, String value2) {
            addCriterion("Location not between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andClassificationnumberIsNull() {
            addCriterion("ClassificationNumber is null");
            return (Criteria) this;
        }

        public Criteria andClassificationnumberIsNotNull() {
            addCriterion("ClassificationNumber is not null");
            return (Criteria) this;
        }

        public Criteria andClassificationnumberEqualTo(String value) {
            addCriterion("ClassificationNumber =", value, "classificationnumber");
            return (Criteria) this;
        }

        public Criteria andClassificationnumberNotEqualTo(String value) {
            addCriterion("ClassificationNumber <>", value, "classificationnumber");
            return (Criteria) this;
        }

        public Criteria andClassificationnumberGreaterThan(String value) {
            addCriterion("ClassificationNumber >", value, "classificationnumber");
            return (Criteria) this;
        }

        public Criteria andClassificationnumberGreaterThanOrEqualTo(String value) {
            addCriterion("ClassificationNumber >=", value, "classificationnumber");
            return (Criteria) this;
        }

        public Criteria andClassificationnumberLessThan(String value) {
            addCriterion("ClassificationNumber <", value, "classificationnumber");
            return (Criteria) this;
        }

        public Criteria andClassificationnumberLessThanOrEqualTo(String value) {
            addCriterion("ClassificationNumber <=", value, "classificationnumber");
            return (Criteria) this;
        }

        public Criteria andClassificationnumberLike(String value) {
            addCriterion("ClassificationNumber like", value, "classificationnumber");
            return (Criteria) this;
        }

        public Criteria andClassificationnumberNotLike(String value) {
            addCriterion("ClassificationNumber not like", value, "classificationnumber");
            return (Criteria) this;
        }

        public Criteria andClassificationnumberIn(List<String> values) {
            addCriterion("ClassificationNumber in", values, "classificationnumber");
            return (Criteria) this;
        }

        public Criteria andClassificationnumberNotIn(List<String> values) {
            addCriterion("ClassificationNumber not in", values, "classificationnumber");
            return (Criteria) this;
        }

        public Criteria andClassificationnumberBetween(String value1, String value2) {
            addCriterion("ClassificationNumber between", value1, value2, "classificationnumber");
            return (Criteria) this;
        }

        public Criteria andClassificationnumberNotBetween(String value1, String value2) {
            addCriterion("ClassificationNumber not between", value1, value2, "classificationnumber");
            return (Criteria) this;
        }

        public Criteria andMainclassificationnumberIsNull() {
            addCriterion("MainClassificationNumber is null");
            return (Criteria) this;
        }

        public Criteria andMainclassificationnumberIsNotNull() {
            addCriterion("MainClassificationNumber is not null");
            return (Criteria) this;
        }

        public Criteria andMainclassificationnumberEqualTo(String value) {
            addCriterion("MainClassificationNumber =", value, "mainclassificationnumber");
            return (Criteria) this;
        }

        public Criteria andMainclassificationnumberNotEqualTo(String value) {
            addCriterion("MainClassificationNumber <>", value, "mainclassificationnumber");
            return (Criteria) this;
        }

        public Criteria andMainclassificationnumberGreaterThan(String value) {
            addCriterion("MainClassificationNumber >", value, "mainclassificationnumber");
            return (Criteria) this;
        }

        public Criteria andMainclassificationnumberGreaterThanOrEqualTo(String value) {
            addCriterion("MainClassificationNumber >=", value, "mainclassificationnumber");
            return (Criteria) this;
        }

        public Criteria andMainclassificationnumberLessThan(String value) {
            addCriterion("MainClassificationNumber <", value, "mainclassificationnumber");
            return (Criteria) this;
        }

        public Criteria andMainclassificationnumberLessThanOrEqualTo(String value) {
            addCriterion("MainClassificationNumber <=", value, "mainclassificationnumber");
            return (Criteria) this;
        }

        public Criteria andMainclassificationnumberLike(String value) {
            addCriterion("MainClassificationNumber like", value, "mainclassificationnumber");
            return (Criteria) this;
        }

        public Criteria andMainclassificationnumberNotLike(String value) {
            addCriterion("MainClassificationNumber not like", value, "mainclassificationnumber");
            return (Criteria) this;
        }

        public Criteria andMainclassificationnumberIn(List<String> values) {
            addCriterion("MainClassificationNumber in", values, "mainclassificationnumber");
            return (Criteria) this;
        }

        public Criteria andMainclassificationnumberNotIn(List<String> values) {
            addCriterion("MainClassificationNumber not in", values, "mainclassificationnumber");
            return (Criteria) this;
        }

        public Criteria andMainclassificationnumberBetween(String value1, String value2) {
            addCriterion("MainClassificationNumber between", value1, value2, "mainclassificationnumber");
            return (Criteria) this;
        }

        public Criteria andMainclassificationnumberNotBetween(String value1, String value2) {
            addCriterion("MainClassificationNumber not between", value1, value2, "mainclassificationnumber");
            return (Criteria) this;
        }

        public Criteria andInventorIsNull() {
            addCriterion("Inventor is null");
            return (Criteria) this;
        }

        public Criteria andInventorIsNotNull() {
            addCriterion("Inventor is not null");
            return (Criteria) this;
        }

        public Criteria andInventorEqualTo(String value) {
            addCriterion("Inventor =", value, "inventor");
            return (Criteria) this;
        }

        public Criteria andInventorNotEqualTo(String value) {
            addCriterion("Inventor <>", value, "inventor");
            return (Criteria) this;
        }

        public Criteria andInventorGreaterThan(String value) {
            addCriterion("Inventor >", value, "inventor");
            return (Criteria) this;
        }

        public Criteria andInventorGreaterThanOrEqualTo(String value) {
            addCriterion("Inventor >=", value, "inventor");
            return (Criteria) this;
        }

        public Criteria andInventorLessThan(String value) {
            addCriterion("Inventor <", value, "inventor");
            return (Criteria) this;
        }

        public Criteria andInventorLessThanOrEqualTo(String value) {
            addCriterion("Inventor <=", value, "inventor");
            return (Criteria) this;
        }

        public Criteria andInventorLike(String value) {
            addCriterion("Inventor like", value, "inventor");
            return (Criteria) this;
        }

        public Criteria andInventorNotLike(String value) {
            addCriterion("Inventor not like", value, "inventor");
            return (Criteria) this;
        }

        public Criteria andInventorIn(List<String> values) {
            addCriterion("Inventor in", values, "inventor");
            return (Criteria) this;
        }

        public Criteria andInventorNotIn(List<String> values) {
            addCriterion("Inventor not in", values, "inventor");
            return (Criteria) this;
        }

        public Criteria andInventorBetween(String value1, String value2) {
            addCriterion("Inventor between", value1, value2, "inventor");
            return (Criteria) this;
        }

        public Criteria andInventorNotBetween(String value1, String value2) {
            addCriterion("Inventor not between", value1, value2, "inventor");
            return (Criteria) this;
        }

        public Criteria andPublishdateIsNull() {
            addCriterion("PublishDate is null");
            return (Criteria) this;
        }

        public Criteria andPublishdateIsNotNull() {
            addCriterion("PublishDate is not null");
            return (Criteria) this;
        }

        public Criteria andPublishdateEqualTo(Date value) {
            addCriterionForJDBCDate("PublishDate =", value, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("PublishDate <>", value, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateGreaterThan(Date value) {
            addCriterionForJDBCDate("PublishDate >", value, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("PublishDate >=", value, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateLessThan(Date value) {
            addCriterionForJDBCDate("PublishDate <", value, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("PublishDate <=", value, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateIn(List<Date> values) {
            addCriterionForJDBCDate("PublishDate in", values, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("PublishDate not in", values, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("PublishDate between", value1, value2, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("PublishDate not between", value1, value2, "publishdate");
            return (Criteria) this;
        }

        public Criteria andApplicantIsNull() {
            addCriterion("Applicant is null");
            return (Criteria) this;
        }

        public Criteria andApplicantIsNotNull() {
            addCriterion("Applicant is not null");
            return (Criteria) this;
        }

        public Criteria andApplicantEqualTo(String value) {
            addCriterion("Applicant =", value, "applicant");
            return (Criteria) this;
        }

        public Criteria andApplicantNotEqualTo(String value) {
            addCriterion("Applicant <>", value, "applicant");
            return (Criteria) this;
        }

        public Criteria andApplicantGreaterThan(String value) {
            addCriterion("Applicant >", value, "applicant");
            return (Criteria) this;
        }

        public Criteria andApplicantGreaterThanOrEqualTo(String value) {
            addCriterion("Applicant >=", value, "applicant");
            return (Criteria) this;
        }

        public Criteria andApplicantLessThan(String value) {
            addCriterion("Applicant <", value, "applicant");
            return (Criteria) this;
        }

        public Criteria andApplicantLessThanOrEqualTo(String value) {
            addCriterion("Applicant <=", value, "applicant");
            return (Criteria) this;
        }

        public Criteria andApplicantLike(String value) {
            addCriterion("Applicant like", value, "applicant");
            return (Criteria) this;
        }

        public Criteria andApplicantNotLike(String value) {
            addCriterion("Applicant not like", value, "applicant");
            return (Criteria) this;
        }

        public Criteria andApplicantIn(List<String> values) {
            addCriterion("Applicant in", values, "applicant");
            return (Criteria) this;
        }

        public Criteria andApplicantNotIn(List<String> values) {
            addCriterion("Applicant not in", values, "applicant");
            return (Criteria) this;
        }

        public Criteria andApplicantBetween(String value1, String value2) {
            addCriterion("Applicant between", value1, value2, "applicant");
            return (Criteria) this;
        }

        public Criteria andApplicantNotBetween(String value1, String value2) {
            addCriterion("Applicant not between", value1, value2, "applicant");
            return (Criteria) this;
        }

        public Criteria andCurrentobligeeIsNull() {
            addCriterion("CurrentObligee is null");
            return (Criteria) this;
        }

        public Criteria andCurrentobligeeIsNotNull() {
            addCriterion("CurrentObligee is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentobligeeEqualTo(String value) {
            addCriterion("CurrentObligee =", value, "currentobligee");
            return (Criteria) this;
        }

        public Criteria andCurrentobligeeNotEqualTo(String value) {
            addCriterion("CurrentObligee <>", value, "currentobligee");
            return (Criteria) this;
        }

        public Criteria andCurrentobligeeGreaterThan(String value) {
            addCriterion("CurrentObligee >", value, "currentobligee");
            return (Criteria) this;
        }

        public Criteria andCurrentobligeeGreaterThanOrEqualTo(String value) {
            addCriterion("CurrentObligee >=", value, "currentobligee");
            return (Criteria) this;
        }

        public Criteria andCurrentobligeeLessThan(String value) {
            addCriterion("CurrentObligee <", value, "currentobligee");
            return (Criteria) this;
        }

        public Criteria andCurrentobligeeLessThanOrEqualTo(String value) {
            addCriterion("CurrentObligee <=", value, "currentobligee");
            return (Criteria) this;
        }

        public Criteria andCurrentobligeeLike(String value) {
            addCriterion("CurrentObligee like", value, "currentobligee");
            return (Criteria) this;
        }

        public Criteria andCurrentobligeeNotLike(String value) {
            addCriterion("CurrentObligee not like", value, "currentobligee");
            return (Criteria) this;
        }

        public Criteria andCurrentobligeeIn(List<String> values) {
            addCriterion("CurrentObligee in", values, "currentobligee");
            return (Criteria) this;
        }

        public Criteria andCurrentobligeeNotIn(List<String> values) {
            addCriterion("CurrentObligee not in", values, "currentobligee");
            return (Criteria) this;
        }

        public Criteria andCurrentobligeeBetween(String value1, String value2) {
            addCriterion("CurrentObligee between", value1, value2, "currentobligee");
            return (Criteria) this;
        }

        public Criteria andCurrentobligeeNotBetween(String value1, String value2) {
            addCriterion("CurrentObligee not between", value1, value2, "currentobligee");
            return (Criteria) this;
        }

        public Criteria andPublishnumberIsNull() {
            addCriterion("PublishNumber is null");
            return (Criteria) this;
        }

        public Criteria andPublishnumberIsNotNull() {
            addCriterion("PublishNumber is not null");
            return (Criteria) this;
        }

        public Criteria andPublishnumberEqualTo(String value) {
            addCriterion("PublishNumber =", value, "publishnumber");
            return (Criteria) this;
        }

        public Criteria andPublishnumberNotEqualTo(String value) {
            addCriterion("PublishNumber <>", value, "publishnumber");
            return (Criteria) this;
        }

        public Criteria andPublishnumberGreaterThan(String value) {
            addCriterion("PublishNumber >", value, "publishnumber");
            return (Criteria) this;
        }

        public Criteria andPublishnumberGreaterThanOrEqualTo(String value) {
            addCriterion("PublishNumber >=", value, "publishnumber");
            return (Criteria) this;
        }

        public Criteria andPublishnumberLessThan(String value) {
            addCriterion("PublishNumber <", value, "publishnumber");
            return (Criteria) this;
        }

        public Criteria andPublishnumberLessThanOrEqualTo(String value) {
            addCriterion("PublishNumber <=", value, "publishnumber");
            return (Criteria) this;
        }

        public Criteria andPublishnumberLike(String value) {
            addCriterion("PublishNumber like", value, "publishnumber");
            return (Criteria) this;
        }

        public Criteria andPublishnumberNotLike(String value) {
            addCriterion("PublishNumber not like", value, "publishnumber");
            return (Criteria) this;
        }

        public Criteria andPublishnumberIn(List<String> values) {
            addCriterion("PublishNumber in", values, "publishnumber");
            return (Criteria) this;
        }

        public Criteria andPublishnumberNotIn(List<String> values) {
            addCriterion("PublishNumber not in", values, "publishnumber");
            return (Criteria) this;
        }

        public Criteria andPublishnumberBetween(String value1, String value2) {
            addCriterion("PublishNumber between", value1, value2, "publishnumber");
            return (Criteria) this;
        }

        public Criteria andPublishnumberNotBetween(String value1, String value2) {
            addCriterion("PublishNumber not between", value1, value2, "publishnumber");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("Title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("Title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("Title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("Title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("Title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("Title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("Title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("Title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("Title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("Title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("Title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("Title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("Title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("Title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("State is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("State is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("State =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("State <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("State >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("State >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("State <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("State <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("State like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("State not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("State in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("State not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("State between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("State not between", value1, value2, "state");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Patent
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Patent
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}