package cn.edu.buaa.scholarshipserver.models;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ProjectExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Project
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Project
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Project
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbggenerated
     */
    public ProjectExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Project
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Project
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andProjectidIsNull() {
            addCriterion("ProjectId is null");
            return (Criteria) this;
        }

        public Criteria andProjectidIsNotNull() {
            addCriterion("ProjectId is not null");
            return (Criteria) this;
        }

        public Criteria andProjectidEqualTo(Long value) {
            addCriterion("ProjectId =", value, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidNotEqualTo(Long value) {
            addCriterion("ProjectId <>", value, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidGreaterThan(Long value) {
            addCriterion("ProjectId >", value, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidGreaterThanOrEqualTo(Long value) {
            addCriterion("ProjectId >=", value, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidLessThan(Long value) {
            addCriterion("ProjectId <", value, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidLessThanOrEqualTo(Long value) {
            addCriterion("ProjectId <=", value, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidIn(List<Long> values) {
            addCriterion("ProjectId in", values, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidNotIn(List<Long> values) {
            addCriterion("ProjectId not in", values, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidBetween(Long value1, Long value2) {
            addCriterion("ProjectId between", value1, value2, "projectid");
            return (Criteria) this;
        }

        public Criteria andProjectidNotBetween(Long value1, Long value2) {
            addCriterion("ProjectId not between", value1, value2, "projectid");
            return (Criteria) this;
        }

        public Criteria andOrganizationIsNull() {
            addCriterion("Organization is null");
            return (Criteria) this;
        }

        public Criteria andOrganizationIsNotNull() {
            addCriterion("Organization is not null");
            return (Criteria) this;
        }

        public Criteria andOrganizationEqualTo(String value) {
            addCriterion("Organization =", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationNotEqualTo(String value) {
            addCriterion("Organization <>", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationGreaterThan(String value) {
            addCriterion("Organization >", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationGreaterThanOrEqualTo(String value) {
            addCriterion("Organization >=", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationLessThan(String value) {
            addCriterion("Organization <", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationLessThanOrEqualTo(String value) {
            addCriterion("Organization <=", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationLike(String value) {
            addCriterion("Organization like", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationNotLike(String value) {
            addCriterion("Organization not like", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationIn(List<String> values) {
            addCriterion("Organization in", values, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationNotIn(List<String> values) {
            addCriterion("Organization not in", values, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationBetween(String value1, String value2) {
            addCriterion("Organization between", value1, value2, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationNotBetween(String value1, String value2) {
            addCriterion("Organization not between", value1, value2, "organization");
            return (Criteria) this;
        }

        public Criteria andFundprojectcodeIsNull() {
            addCriterion("FundProjectCode is null");
            return (Criteria) this;
        }

        public Criteria andFundprojectcodeIsNotNull() {
            addCriterion("FundProjectCode is not null");
            return (Criteria) this;
        }

        public Criteria andFundprojectcodeEqualTo(String value) {
            addCriterion("FundProjectCode =", value, "fundprojectcode");
            return (Criteria) this;
        }

        public Criteria andFundprojectcodeNotEqualTo(String value) {
            addCriterion("FundProjectCode <>", value, "fundprojectcode");
            return (Criteria) this;
        }

        public Criteria andFundprojectcodeGreaterThan(String value) {
            addCriterion("FundProjectCode >", value, "fundprojectcode");
            return (Criteria) this;
        }

        public Criteria andFundprojectcodeGreaterThanOrEqualTo(String value) {
            addCriterion("FundProjectCode >=", value, "fundprojectcode");
            return (Criteria) this;
        }

        public Criteria andFundprojectcodeLessThan(String value) {
            addCriterion("FundProjectCode <", value, "fundprojectcode");
            return (Criteria) this;
        }

        public Criteria andFundprojectcodeLessThanOrEqualTo(String value) {
            addCriterion("FundProjectCode <=", value, "fundprojectcode");
            return (Criteria) this;
        }

        public Criteria andFundprojectcodeLike(String value) {
            addCriterion("FundProjectCode like", value, "fundprojectcode");
            return (Criteria) this;
        }

        public Criteria andFundprojectcodeNotLike(String value) {
            addCriterion("FundProjectCode not like", value, "fundprojectcode");
            return (Criteria) this;
        }

        public Criteria andFundprojectcodeIn(List<String> values) {
            addCriterion("FundProjectCode in", values, "fundprojectcode");
            return (Criteria) this;
        }

        public Criteria andFundprojectcodeNotIn(List<String> values) {
            addCriterion("FundProjectCode not in", values, "fundprojectcode");
            return (Criteria) this;
        }

        public Criteria andFundprojectcodeBetween(String value1, String value2) {
            addCriterion("FundProjectCode between", value1, value2, "fundprojectcode");
            return (Criteria) this;
        }

        public Criteria andFundprojectcodeNotBetween(String value1, String value2) {
            addCriterion("FundProjectCode not between", value1, value2, "fundprojectcode");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("Source is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("Source is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("Source =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("Source <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("Source >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("Source >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("Source <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("Source <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("Source like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("Source not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("Source in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("Source not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("Source between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("Source not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andDoiIsNull() {
            addCriterion("Doi is null");
            return (Criteria) this;
        }

        public Criteria andDoiIsNotNull() {
            addCriterion("Doi is not null");
            return (Criteria) this;
        }

        public Criteria andDoiEqualTo(String value) {
            addCriterion("Doi =", value, "doi");
            return (Criteria) this;
        }

        public Criteria andDoiNotEqualTo(String value) {
            addCriterion("Doi <>", value, "doi");
            return (Criteria) this;
        }

        public Criteria andDoiGreaterThan(String value) {
            addCriterion("Doi >", value, "doi");
            return (Criteria) this;
        }

        public Criteria andDoiGreaterThanOrEqualTo(String value) {
            addCriterion("Doi >=", value, "doi");
            return (Criteria) this;
        }

        public Criteria andDoiLessThan(String value) {
            addCriterion("Doi <", value, "doi");
            return (Criteria) this;
        }

        public Criteria andDoiLessThanOrEqualTo(String value) {
            addCriterion("Doi <=", value, "doi");
            return (Criteria) this;
        }

        public Criteria andDoiLike(String value) {
            addCriterion("Doi like", value, "doi");
            return (Criteria) this;
        }

        public Criteria andDoiNotLike(String value) {
            addCriterion("Doi not like", value, "doi");
            return (Criteria) this;
        }

        public Criteria andDoiIn(List<String> values) {
            addCriterion("Doi in", values, "doi");
            return (Criteria) this;
        }

        public Criteria andDoiNotIn(List<String> values) {
            addCriterion("Doi not in", values, "doi");
            return (Criteria) this;
        }

        public Criteria andDoiBetween(String value1, String value2) {
            addCriterion("Doi between", value1, value2, "doi");
            return (Criteria) this;
        }

        public Criteria andDoiNotBetween(String value1, String value2) {
            addCriterion("Doi not between", value1, value2, "doi");
            return (Criteria) this;
        }

        public Criteria andFieldnameIsNull() {
            addCriterion("FieldName is null");
            return (Criteria) this;
        }

        public Criteria andFieldnameIsNotNull() {
            addCriterion("FieldName is not null");
            return (Criteria) this;
        }

        public Criteria andFieldnameEqualTo(String value) {
            addCriterion("FieldName =", value, "fieldname");
            return (Criteria) this;
        }

        public Criteria andFieldnameNotEqualTo(String value) {
            addCriterion("FieldName <>", value, "fieldname");
            return (Criteria) this;
        }

        public Criteria andFieldnameGreaterThan(String value) {
            addCriterion("FieldName >", value, "fieldname");
            return (Criteria) this;
        }

        public Criteria andFieldnameGreaterThanOrEqualTo(String value) {
            addCriterion("FieldName >=", value, "fieldname");
            return (Criteria) this;
        }

        public Criteria andFieldnameLessThan(String value) {
            addCriterion("FieldName <", value, "fieldname");
            return (Criteria) this;
        }

        public Criteria andFieldnameLessThanOrEqualTo(String value) {
            addCriterion("FieldName <=", value, "fieldname");
            return (Criteria) this;
        }

        public Criteria andFieldnameLike(String value) {
            addCriterion("FieldName like", value, "fieldname");
            return (Criteria) this;
        }

        public Criteria andFieldnameNotLike(String value) {
            addCriterion("FieldName not like", value, "fieldname");
            return (Criteria) this;
        }

        public Criteria andFieldnameIn(List<String> values) {
            addCriterion("FieldName in", values, "fieldname");
            return (Criteria) this;
        }

        public Criteria andFieldnameNotIn(List<String> values) {
            addCriterion("FieldName not in", values, "fieldname");
            return (Criteria) this;
        }

        public Criteria andFieldnameBetween(String value1, String value2) {
            addCriterion("FieldName between", value1, value2, "fieldname");
            return (Criteria) this;
        }

        public Criteria andFieldnameNotBetween(String value1, String value2) {
            addCriterion("FieldName not between", value1, value2, "fieldname");
            return (Criteria) this;
        }

        public Criteria andDoiurlIsNull() {
            addCriterion("DoiUrl is null");
            return (Criteria) this;
        }

        public Criteria andDoiurlIsNotNull() {
            addCriterion("DoiUrl is not null");
            return (Criteria) this;
        }

        public Criteria andDoiurlEqualTo(String value) {
            addCriterion("DoiUrl =", value, "doiurl");
            return (Criteria) this;
        }

        public Criteria andDoiurlNotEqualTo(String value) {
            addCriterion("DoiUrl <>", value, "doiurl");
            return (Criteria) this;
        }

        public Criteria andDoiurlGreaterThan(String value) {
            addCriterion("DoiUrl >", value, "doiurl");
            return (Criteria) this;
        }

        public Criteria andDoiurlGreaterThanOrEqualTo(String value) {
            addCriterion("DoiUrl >=", value, "doiurl");
            return (Criteria) this;
        }

        public Criteria andDoiurlLessThan(String value) {
            addCriterion("DoiUrl <", value, "doiurl");
            return (Criteria) this;
        }

        public Criteria andDoiurlLessThanOrEqualTo(String value) {
            addCriterion("DoiUrl <=", value, "doiurl");
            return (Criteria) this;
        }

        public Criteria andDoiurlLike(String value) {
            addCriterion("DoiUrl like", value, "doiurl");
            return (Criteria) this;
        }

        public Criteria andDoiurlNotLike(String value) {
            addCriterion("DoiUrl not like", value, "doiurl");
            return (Criteria) this;
        }

        public Criteria andDoiurlIn(List<String> values) {
            addCriterion("DoiUrl in", values, "doiurl");
            return (Criteria) this;
        }

        public Criteria andDoiurlNotIn(List<String> values) {
            addCriterion("DoiUrl not in", values, "doiurl");
            return (Criteria) this;
        }

        public Criteria andDoiurlBetween(String value1, String value2) {
            addCriterion("DoiUrl between", value1, value2, "doiurl");
            return (Criteria) this;
        }

        public Criteria andDoiurlNotBetween(String value1, String value2) {
            addCriterion("DoiUrl not between", value1, value2, "doiurl");
            return (Criteria) this;
        }

        public Criteria andZhabstractIsNull() {
            addCriterion("ZhAbstract is null");
            return (Criteria) this;
        }

        public Criteria andZhabstractIsNotNull() {
            addCriterion("ZhAbstract is not null");
            return (Criteria) this;
        }

        public Criteria andZhabstractEqualTo(String value) {
            addCriterion("ZhAbstract =", value, "zhabstract");
            return (Criteria) this;
        }

        public Criteria andZhabstractNotEqualTo(String value) {
            addCriterion("ZhAbstract <>", value, "zhabstract");
            return (Criteria) this;
        }

        public Criteria andZhabstractGreaterThan(String value) {
            addCriterion("ZhAbstract >", value, "zhabstract");
            return (Criteria) this;
        }

        public Criteria andZhabstractGreaterThanOrEqualTo(String value) {
            addCriterion("ZhAbstract >=", value, "zhabstract");
            return (Criteria) this;
        }

        public Criteria andZhabstractLessThan(String value) {
            addCriterion("ZhAbstract <", value, "zhabstract");
            return (Criteria) this;
        }

        public Criteria andZhabstractLessThanOrEqualTo(String value) {
            addCriterion("ZhAbstract <=", value, "zhabstract");
            return (Criteria) this;
        }

        public Criteria andZhabstractLike(String value) {
            addCriterion("ZhAbstract like", value, "zhabstract");
            return (Criteria) this;
        }

        public Criteria andZhabstractNotLike(String value) {
            addCriterion("ZhAbstract not like", value, "zhabstract");
            return (Criteria) this;
        }

        public Criteria andZhabstractIn(List<String> values) {
            addCriterion("ZhAbstract in", values, "zhabstract");
            return (Criteria) this;
        }

        public Criteria andZhabstractNotIn(List<String> values) {
            addCriterion("ZhAbstract not in", values, "zhabstract");
            return (Criteria) this;
        }

        public Criteria andZhabstractBetween(String value1, String value2) {
            addCriterion("ZhAbstract between", value1, value2, "zhabstract");
            return (Criteria) this;
        }

        public Criteria andZhabstractNotBetween(String value1, String value2) {
            addCriterion("ZhAbstract not between", value1, value2, "zhabstract");
            return (Criteria) this;
        }

        public Criteria andFundprojectIsNull() {
            addCriterion("FundProject is null");
            return (Criteria) this;
        }

        public Criteria andFundprojectIsNotNull() {
            addCriterion("FundProject is not null");
            return (Criteria) this;
        }

        public Criteria andFundprojectEqualTo(String value) {
            addCriterion("FundProject =", value, "fundproject");
            return (Criteria) this;
        }

        public Criteria andFundprojectNotEqualTo(String value) {
            addCriterion("FundProject <>", value, "fundproject");
            return (Criteria) this;
        }

        public Criteria andFundprojectGreaterThan(String value) {
            addCriterion("FundProject >", value, "fundproject");
            return (Criteria) this;
        }

        public Criteria andFundprojectGreaterThanOrEqualTo(String value) {
            addCriterion("FundProject >=", value, "fundproject");
            return (Criteria) this;
        }

        public Criteria andFundprojectLessThan(String value) {
            addCriterion("FundProject <", value, "fundproject");
            return (Criteria) this;
        }

        public Criteria andFundprojectLessThanOrEqualTo(String value) {
            addCriterion("FundProject <=", value, "fundproject");
            return (Criteria) this;
        }

        public Criteria andFundprojectLike(String value) {
            addCriterion("FundProject like", value, "fundproject");
            return (Criteria) this;
        }

        public Criteria andFundprojectNotLike(String value) {
            addCriterion("FundProject not like", value, "fundproject");
            return (Criteria) this;
        }

        public Criteria andFundprojectIn(List<String> values) {
            addCriterion("FundProject in", values, "fundproject");
            return (Criteria) this;
        }

        public Criteria andFundprojectNotIn(List<String> values) {
            addCriterion("FundProject not in", values, "fundproject");
            return (Criteria) this;
        }

        public Criteria andFundprojectBetween(String value1, String value2) {
            addCriterion("FundProject between", value1, value2, "fundproject");
            return (Criteria) this;
        }

        public Criteria andFundprojectNotBetween(String value1, String value2) {
            addCriterion("FundProject not between", value1, value2, "fundproject");
            return (Criteria) this;
        }

        public Criteria andProjectauthorsIsNull() {
            addCriterion("ProjectAuthors is null");
            return (Criteria) this;
        }

        public Criteria andProjectauthorsIsNotNull() {
            addCriterion("ProjectAuthors is not null");
            return (Criteria) this;
        }

        public Criteria andProjectauthorsEqualTo(String value) {
            addCriterion("ProjectAuthors =", value, "projectauthors");
            return (Criteria) this;
        }

        public Criteria andProjectauthorsNotEqualTo(String value) {
            addCriterion("ProjectAuthors <>", value, "projectauthors");
            return (Criteria) this;
        }

        public Criteria andProjectauthorsGreaterThan(String value) {
            addCriterion("ProjectAuthors >", value, "projectauthors");
            return (Criteria) this;
        }

        public Criteria andProjectauthorsGreaterThanOrEqualTo(String value) {
            addCriterion("ProjectAuthors >=", value, "projectauthors");
            return (Criteria) this;
        }

        public Criteria andProjectauthorsLessThan(String value) {
            addCriterion("ProjectAuthors <", value, "projectauthors");
            return (Criteria) this;
        }

        public Criteria andProjectauthorsLessThanOrEqualTo(String value) {
            addCriterion("ProjectAuthors <=", value, "projectauthors");
            return (Criteria) this;
        }

        public Criteria andProjectauthorsLike(String value) {
            addCriterion("ProjectAuthors like", value, "projectauthors");
            return (Criteria) this;
        }

        public Criteria andProjectauthorsNotLike(String value) {
            addCriterion("ProjectAuthors not like", value, "projectauthors");
            return (Criteria) this;
        }

        public Criteria andProjectauthorsIn(List<String> values) {
            addCriterion("ProjectAuthors in", values, "projectauthors");
            return (Criteria) this;
        }

        public Criteria andProjectauthorsNotIn(List<String> values) {
            addCriterion("ProjectAuthors not in", values, "projectauthors");
            return (Criteria) this;
        }

        public Criteria andProjectauthorsBetween(String value1, String value2) {
            addCriterion("ProjectAuthors between", value1, value2, "projectauthors");
            return (Criteria) this;
        }

        public Criteria andProjectauthorsNotBetween(String value1, String value2) {
            addCriterion("ProjectAuthors not between", value1, value2, "projectauthors");
            return (Criteria) this;
        }

        public Criteria andFieldcodeIsNull() {
            addCriterion("FieldCode is null");
            return (Criteria) this;
        }

        public Criteria andFieldcodeIsNotNull() {
            addCriterion("FieldCode is not null");
            return (Criteria) this;
        }

        public Criteria andFieldcodeEqualTo(String value) {
            addCriterion("FieldCode =", value, "fieldcode");
            return (Criteria) this;
        }

        public Criteria andFieldcodeNotEqualTo(String value) {
            addCriterion("FieldCode <>", value, "fieldcode");
            return (Criteria) this;
        }

        public Criteria andFieldcodeGreaterThan(String value) {
            addCriterion("FieldCode >", value, "fieldcode");
            return (Criteria) this;
        }

        public Criteria andFieldcodeGreaterThanOrEqualTo(String value) {
            addCriterion("FieldCode >=", value, "fieldcode");
            return (Criteria) this;
        }

        public Criteria andFieldcodeLessThan(String value) {
            addCriterion("FieldCode <", value, "fieldcode");
            return (Criteria) this;
        }

        public Criteria andFieldcodeLessThanOrEqualTo(String value) {
            addCriterion("FieldCode <=", value, "fieldcode");
            return (Criteria) this;
        }

        public Criteria andFieldcodeLike(String value) {
            addCriterion("FieldCode like", value, "fieldcode");
            return (Criteria) this;
        }

        public Criteria andFieldcodeNotLike(String value) {
            addCriterion("FieldCode not like", value, "fieldcode");
            return (Criteria) this;
        }

        public Criteria andFieldcodeIn(List<String> values) {
            addCriterion("FieldCode in", values, "fieldcode");
            return (Criteria) this;
        }

        public Criteria andFieldcodeNotIn(List<String> values) {
            addCriterion("FieldCode not in", values, "fieldcode");
            return (Criteria) this;
        }

        public Criteria andFieldcodeBetween(String value1, String value2) {
            addCriterion("FieldCode between", value1, value2, "fieldcode");
            return (Criteria) this;
        }

        public Criteria andFieldcodeNotBetween(String value1, String value2) {
            addCriterion("FieldCode not between", value1, value2, "fieldcode");
            return (Criteria) this;
        }

        public Criteria andOrganizationidIsNull() {
            addCriterion("OrganizationId is null");
            return (Criteria) this;
        }

        public Criteria andOrganizationidIsNotNull() {
            addCriterion("OrganizationId is not null");
            return (Criteria) this;
        }

        public Criteria andOrganizationidEqualTo(String value) {
            addCriterion("OrganizationId =", value, "organizationid");
            return (Criteria) this;
        }

        public Criteria andOrganizationidNotEqualTo(String value) {
            addCriterion("OrganizationId <>", value, "organizationid");
            return (Criteria) this;
        }

        public Criteria andOrganizationidGreaterThan(String value) {
            addCriterion("OrganizationId >", value, "organizationid");
            return (Criteria) this;
        }

        public Criteria andOrganizationidGreaterThanOrEqualTo(String value) {
            addCriterion("OrganizationId >=", value, "organizationid");
            return (Criteria) this;
        }

        public Criteria andOrganizationidLessThan(String value) {
            addCriterion("OrganizationId <", value, "organizationid");
            return (Criteria) this;
        }

        public Criteria andOrganizationidLessThanOrEqualTo(String value) {
            addCriterion("OrganizationId <=", value, "organizationid");
            return (Criteria) this;
        }

        public Criteria andOrganizationidLike(String value) {
            addCriterion("OrganizationId like", value, "organizationid");
            return (Criteria) this;
        }

        public Criteria andOrganizationidNotLike(String value) {
            addCriterion("OrganizationId not like", value, "organizationid");
            return (Criteria) this;
        }

        public Criteria andOrganizationidIn(List<String> values) {
            addCriterion("OrganizationId in", values, "organizationid");
            return (Criteria) this;
        }

        public Criteria andOrganizationidNotIn(List<String> values) {
            addCriterion("OrganizationId not in", values, "organizationid");
            return (Criteria) this;
        }

        public Criteria andOrganizationidBetween(String value1, String value2) {
            addCriterion("OrganizationId between", value1, value2, "organizationid");
            return (Criteria) this;
        }

        public Criteria andOrganizationidNotBetween(String value1, String value2) {
            addCriterion("OrganizationId not between", value1, value2, "organizationid");
            return (Criteria) this;
        }

        public Criteria andSupporttypenameIsNull() {
            addCriterion("SupportTypeName is null");
            return (Criteria) this;
        }

        public Criteria andSupporttypenameIsNotNull() {
            addCriterion("SupportTypeName is not null");
            return (Criteria) this;
        }

        public Criteria andSupporttypenameEqualTo(String value) {
            addCriterion("SupportTypeName =", value, "supporttypename");
            return (Criteria) this;
        }

        public Criteria andSupporttypenameNotEqualTo(String value) {
            addCriterion("SupportTypeName <>", value, "supporttypename");
            return (Criteria) this;
        }

        public Criteria andSupporttypenameGreaterThan(String value) {
            addCriterion("SupportTypeName >", value, "supporttypename");
            return (Criteria) this;
        }

        public Criteria andSupporttypenameGreaterThanOrEqualTo(String value) {
            addCriterion("SupportTypeName >=", value, "supporttypename");
            return (Criteria) this;
        }

        public Criteria andSupporttypenameLessThan(String value) {
            addCriterion("SupportTypeName <", value, "supporttypename");
            return (Criteria) this;
        }

        public Criteria andSupporttypenameLessThanOrEqualTo(String value) {
            addCriterion("SupportTypeName <=", value, "supporttypename");
            return (Criteria) this;
        }

        public Criteria andSupporttypenameLike(String value) {
            addCriterion("SupportTypeName like", value, "supporttypename");
            return (Criteria) this;
        }

        public Criteria andSupporttypenameNotLike(String value) {
            addCriterion("SupportTypeName not like", value, "supporttypename");
            return (Criteria) this;
        }

        public Criteria andSupporttypenameIn(List<String> values) {
            addCriterion("SupportTypeName in", values, "supporttypename");
            return (Criteria) this;
        }

        public Criteria andSupporttypenameNotIn(List<String> values) {
            addCriterion("SupportTypeName not in", values, "supporttypename");
            return (Criteria) this;
        }

        public Criteria andSupporttypenameBetween(String value1, String value2) {
            addCriterion("SupportTypeName between", value1, value2, "supporttypename");
            return (Criteria) this;
        }

        public Criteria andSupporttypenameNotBetween(String value1, String value2) {
            addCriterion("SupportTypeName not between", value1, value2, "supporttypename");
            return (Criteria) this;
        }

        public Criteria andChinesetitleIsNull() {
            addCriterion("ChineseTitle is null");
            return (Criteria) this;
        }

        public Criteria andChinesetitleIsNotNull() {
            addCriterion("ChineseTitle is not null");
            return (Criteria) this;
        }

        public Criteria andChinesetitleEqualTo(String value) {
            addCriterion("ChineseTitle =", value, "chinesetitle");
            return (Criteria) this;
        }

        public Criteria andChinesetitleNotEqualTo(String value) {
            addCriterion("ChineseTitle <>", value, "chinesetitle");
            return (Criteria) this;
        }

        public Criteria andChinesetitleGreaterThan(String value) {
            addCriterion("ChineseTitle >", value, "chinesetitle");
            return (Criteria) this;
        }

        public Criteria andChinesetitleGreaterThanOrEqualTo(String value) {
            addCriterion("ChineseTitle >=", value, "chinesetitle");
            return (Criteria) this;
        }

        public Criteria andChinesetitleLessThan(String value) {
            addCriterion("ChineseTitle <", value, "chinesetitle");
            return (Criteria) this;
        }

        public Criteria andChinesetitleLessThanOrEqualTo(String value) {
            addCriterion("ChineseTitle <=", value, "chinesetitle");
            return (Criteria) this;
        }

        public Criteria andChinesetitleLike(String value) {
            addCriterion("ChineseTitle like", value, "chinesetitle");
            return (Criteria) this;
        }

        public Criteria andChinesetitleNotLike(String value) {
            addCriterion("ChineseTitle not like", value, "chinesetitle");
            return (Criteria) this;
        }

        public Criteria andChinesetitleIn(List<String> values) {
            addCriterion("ChineseTitle in", values, "chinesetitle");
            return (Criteria) this;
        }

        public Criteria andChinesetitleNotIn(List<String> values) {
            addCriterion("ChineseTitle not in", values, "chinesetitle");
            return (Criteria) this;
        }

        public Criteria andChinesetitleBetween(String value1, String value2) {
            addCriterion("ChineseTitle between", value1, value2, "chinesetitle");
            return (Criteria) this;
        }

        public Criteria andChinesetitleNotBetween(String value1, String value2) {
            addCriterion("ChineseTitle not between", value1, value2, "chinesetitle");
            return (Criteria) this;
        }

        public Criteria andPublishdateIsNull() {
            addCriterion("PublishDate is null");
            return (Criteria) this;
        }

        public Criteria andPublishdateIsNotNull() {
            addCriterion("PublishDate is not null");
            return (Criteria) this;
        }

        public Criteria andPublishdateEqualTo(Date value) {
            addCriterionForJDBCDate("PublishDate =", value, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("PublishDate <>", value, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateGreaterThan(Date value) {
            addCriterionForJDBCDate("PublishDate >", value, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("PublishDate >=", value, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateLessThan(Date value) {
            addCriterionForJDBCDate("PublishDate <", value, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("PublishDate <=", value, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateIn(List<Date> values) {
            addCriterionForJDBCDate("PublishDate in", values, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("PublishDate not in", values, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("PublishDate between", value1, value2, "publishdate");
            return (Criteria) this;
        }

        public Criteria andPublishdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("PublishDate not between", value1, value2, "publishdate");
            return (Criteria) this;
        }

        public Criteria andFundprojectnoIsNull() {
            addCriterion("FundProjectNo is null");
            return (Criteria) this;
        }

        public Criteria andFundprojectnoIsNotNull() {
            addCriterion("FundProjectNo is not null");
            return (Criteria) this;
        }

        public Criteria andFundprojectnoEqualTo(String value) {
            addCriterion("FundProjectNo =", value, "fundprojectno");
            return (Criteria) this;
        }

        public Criteria andFundprojectnoNotEqualTo(String value) {
            addCriterion("FundProjectNo <>", value, "fundprojectno");
            return (Criteria) this;
        }

        public Criteria andFundprojectnoGreaterThan(String value) {
            addCriterion("FundProjectNo >", value, "fundprojectno");
            return (Criteria) this;
        }

        public Criteria andFundprojectnoGreaterThanOrEqualTo(String value) {
            addCriterion("FundProjectNo >=", value, "fundprojectno");
            return (Criteria) this;
        }

        public Criteria andFundprojectnoLessThan(String value) {
            addCriterion("FundProjectNo <", value, "fundprojectno");
            return (Criteria) this;
        }

        public Criteria andFundprojectnoLessThanOrEqualTo(String value) {
            addCriterion("FundProjectNo <=", value, "fundprojectno");
            return (Criteria) this;
        }

        public Criteria andFundprojectnoLike(String value) {
            addCriterion("FundProjectNo like", value, "fundprojectno");
            return (Criteria) this;
        }

        public Criteria andFundprojectnoNotLike(String value) {
            addCriterion("FundProjectNo not like", value, "fundprojectno");
            return (Criteria) this;
        }

        public Criteria andFundprojectnoIn(List<String> values) {
            addCriterion("FundProjectNo in", values, "fundprojectno");
            return (Criteria) this;
        }

        public Criteria andFundprojectnoNotIn(List<String> values) {
            addCriterion("FundProjectNo not in", values, "fundprojectno");
            return (Criteria) this;
        }

        public Criteria andFundprojectnoBetween(String value1, String value2) {
            addCriterion("FundProjectNo between", value1, value2, "fundprojectno");
            return (Criteria) this;
        }

        public Criteria andFundprojectnoNotBetween(String value1, String value2) {
            addCriterion("FundProjectNo not between", value1, value2, "fundprojectno");
            return (Criteria) this;
        }

        public Criteria andAchievementidIsNull() {
            addCriterion("AchievementID is null");
            return (Criteria) this;
        }

        public Criteria andAchievementidIsNotNull() {
            addCriterion("AchievementID is not null");
            return (Criteria) this;
        }

        public Criteria andAchievementidEqualTo(String value) {
            addCriterion("AchievementID =", value, "achievementid");
            return (Criteria) this;
        }

        public Criteria andAchievementidNotEqualTo(String value) {
            addCriterion("AchievementID <>", value, "achievementid");
            return (Criteria) this;
        }

        public Criteria andAchievementidGreaterThan(String value) {
            addCriterion("AchievementID >", value, "achievementid");
            return (Criteria) this;
        }

        public Criteria andAchievementidGreaterThanOrEqualTo(String value) {
            addCriterion("AchievementID >=", value, "achievementid");
            return (Criteria) this;
        }

        public Criteria andAchievementidLessThan(String value) {
            addCriterion("AchievementID <", value, "achievementid");
            return (Criteria) this;
        }

        public Criteria andAchievementidLessThanOrEqualTo(String value) {
            addCriterion("AchievementID <=", value, "achievementid");
            return (Criteria) this;
        }

        public Criteria andAchievementidLike(String value) {
            addCriterion("AchievementID like", value, "achievementid");
            return (Criteria) this;
        }

        public Criteria andAchievementidNotLike(String value) {
            addCriterion("AchievementID not like", value, "achievementid");
            return (Criteria) this;
        }

        public Criteria andAchievementidIn(List<String> values) {
            addCriterion("AchievementID in", values, "achievementid");
            return (Criteria) this;
        }

        public Criteria andAchievementidNotIn(List<String> values) {
            addCriterion("AchievementID not in", values, "achievementid");
            return (Criteria) this;
        }

        public Criteria andAchievementidBetween(String value1, String value2) {
            addCriterion("AchievementID between", value1, value2, "achievementid");
            return (Criteria) this;
        }

        public Criteria andAchievementidNotBetween(String value1, String value2) {
            addCriterion("AchievementID not between", value1, value2, "achievementid");
            return (Criteria) this;
        }

        public Criteria andJournalIsNull() {
            addCriterion("Journal is null");
            return (Criteria) this;
        }

        public Criteria andJournalIsNotNull() {
            addCriterion("Journal is not null");
            return (Criteria) this;
        }

        public Criteria andJournalEqualTo(String value) {
            addCriterion("Journal =", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalNotEqualTo(String value) {
            addCriterion("Journal <>", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalGreaterThan(String value) {
            addCriterion("Journal >", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalGreaterThanOrEqualTo(String value) {
            addCriterion("Journal >=", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalLessThan(String value) {
            addCriterion("Journal <", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalLessThanOrEqualTo(String value) {
            addCriterion("Journal <=", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalLike(String value) {
            addCriterion("Journal like", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalNotLike(String value) {
            addCriterion("Journal not like", value, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalIn(List<String> values) {
            addCriterion("Journal in", values, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalNotIn(List<String> values) {
            addCriterion("Journal not in", values, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalBetween(String value1, String value2) {
            addCriterion("Journal between", value1, value2, "journal");
            return (Criteria) this;
        }

        public Criteria andJournalNotBetween(String value1, String value2) {
            addCriterion("Journal not between", value1, value2, "journal");
            return (Criteria) this;
        }

        public Criteria andProducttypeIsNull() {
            addCriterion("ProductType is null");
            return (Criteria) this;
        }

        public Criteria andProducttypeIsNotNull() {
            addCriterion("ProductType is not null");
            return (Criteria) this;
        }

        public Criteria andProducttypeEqualTo(String value) {
            addCriterion("ProductType =", value, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeNotEqualTo(String value) {
            addCriterion("ProductType <>", value, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeGreaterThan(String value) {
            addCriterion("ProductType >", value, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeGreaterThanOrEqualTo(String value) {
            addCriterion("ProductType >=", value, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeLessThan(String value) {
            addCriterion("ProductType <", value, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeLessThanOrEqualTo(String value) {
            addCriterion("ProductType <=", value, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeLike(String value) {
            addCriterion("ProductType like", value, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeNotLike(String value) {
            addCriterion("ProductType not like", value, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeIn(List<String> values) {
            addCriterion("ProductType in", values, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeNotIn(List<String> values) {
            addCriterion("ProductType not in", values, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeBetween(String value1, String value2) {
            addCriterion("ProductType between", value1, value2, "producttype");
            return (Criteria) this;
        }

        public Criteria andProducttypeNotBetween(String value1, String value2) {
            addCriterion("ProductType not between", value1, value2, "producttype");
            return (Criteria) this;
        }

        public Criteria andZhkeywordIsNull() {
            addCriterion("ZhKeyword is null");
            return (Criteria) this;
        }

        public Criteria andZhkeywordIsNotNull() {
            addCriterion("ZhKeyword is not null");
            return (Criteria) this;
        }

        public Criteria andZhkeywordEqualTo(String value) {
            addCriterion("ZhKeyword =", value, "zhkeyword");
            return (Criteria) this;
        }

        public Criteria andZhkeywordNotEqualTo(String value) {
            addCriterion("ZhKeyword <>", value, "zhkeyword");
            return (Criteria) this;
        }

        public Criteria andZhkeywordGreaterThan(String value) {
            addCriterion("ZhKeyword >", value, "zhkeyword");
            return (Criteria) this;
        }

        public Criteria andZhkeywordGreaterThanOrEqualTo(String value) {
            addCriterion("ZhKeyword >=", value, "zhkeyword");
            return (Criteria) this;
        }

        public Criteria andZhkeywordLessThan(String value) {
            addCriterion("ZhKeyword <", value, "zhkeyword");
            return (Criteria) this;
        }

        public Criteria andZhkeywordLessThanOrEqualTo(String value) {
            addCriterion("ZhKeyword <=", value, "zhkeyword");
            return (Criteria) this;
        }

        public Criteria andZhkeywordLike(String value) {
            addCriterion("ZhKeyword like", value, "zhkeyword");
            return (Criteria) this;
        }

        public Criteria andZhkeywordNotLike(String value) {
            addCriterion("ZhKeyword not like", value, "zhkeyword");
            return (Criteria) this;
        }

        public Criteria andZhkeywordIn(List<String> values) {
            addCriterion("ZhKeyword in", values, "zhkeyword");
            return (Criteria) this;
        }

        public Criteria andZhkeywordNotIn(List<String> values) {
            addCriterion("ZhKeyword not in", values, "zhkeyword");
            return (Criteria) this;
        }

        public Criteria andZhkeywordBetween(String value1, String value2) {
            addCriterion("ZhKeyword between", value1, value2, "zhkeyword");
            return (Criteria) this;
        }

        public Criteria andZhkeywordNotBetween(String value1, String value2) {
            addCriterion("ZhKeyword not between", value1, value2, "zhkeyword");
            return (Criteria) this;
        }

        public Criteria andSupporttypeIsNull() {
            addCriterion("SupportType is null");
            return (Criteria) this;
        }

        public Criteria andSupporttypeIsNotNull() {
            addCriterion("SupportType is not null");
            return (Criteria) this;
        }

        public Criteria andSupporttypeEqualTo(String value) {
            addCriterion("SupportType =", value, "supporttype");
            return (Criteria) this;
        }

        public Criteria andSupporttypeNotEqualTo(String value) {
            addCriterion("SupportType <>", value, "supporttype");
            return (Criteria) this;
        }

        public Criteria andSupporttypeGreaterThan(String value) {
            addCriterion("SupportType >", value, "supporttype");
            return (Criteria) this;
        }

        public Criteria andSupporttypeGreaterThanOrEqualTo(String value) {
            addCriterion("SupportType >=", value, "supporttype");
            return (Criteria) this;
        }

        public Criteria andSupporttypeLessThan(String value) {
            addCriterion("SupportType <", value, "supporttype");
            return (Criteria) this;
        }

        public Criteria andSupporttypeLessThanOrEqualTo(String value) {
            addCriterion("SupportType <=", value, "supporttype");
            return (Criteria) this;
        }

        public Criteria andSupporttypeLike(String value) {
            addCriterion("SupportType like", value, "supporttype");
            return (Criteria) this;
        }

        public Criteria andSupporttypeNotLike(String value) {
            addCriterion("SupportType not like", value, "supporttype");
            return (Criteria) this;
        }

        public Criteria andSupporttypeIn(List<String> values) {
            addCriterion("SupportType in", values, "supporttype");
            return (Criteria) this;
        }

        public Criteria andSupporttypeNotIn(List<String> values) {
            addCriterion("SupportType not in", values, "supporttype");
            return (Criteria) this;
        }

        public Criteria andSupporttypeBetween(String value1, String value2) {
            addCriterion("SupportType between", value1, value2, "supporttype");
            return (Criteria) this;
        }

        public Criteria andSupporttypeNotBetween(String value1, String value2) {
            addCriterion("SupportType not between", value1, value2, "supporttype");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Project
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Project
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}