package cn.edu.buaa.scholarshipserver.models;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ScholarExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Scholar
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Scholar
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Scholar
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Scholar
     *
     * @mbggenerated
     */
    public ScholarExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Scholar
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Scholar
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Scholar
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Scholar
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Scholar
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Scholar
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Scholar
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Scholar
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Scholar
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Scholar
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Scholar
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andScholaridIsNull() {
            addCriterion("ScholarId is null");
            return (Criteria) this;
        }

        public Criteria andScholaridIsNotNull() {
            addCriterion("ScholarId is not null");
            return (Criteria) this;
        }

        public Criteria andScholaridEqualTo(Integer value) {
            addCriterion("ScholarId =", value, "scholarid");
            return (Criteria) this;
        }

        public Criteria andScholaridNotEqualTo(Integer value) {
            addCriterion("ScholarId <>", value, "scholarid");
            return (Criteria) this;
        }

        public Criteria andScholaridGreaterThan(Integer value) {
            addCriterion("ScholarId >", value, "scholarid");
            return (Criteria) this;
        }

        public Criteria andScholaridGreaterThanOrEqualTo(Integer value) {
            addCriterion("ScholarId >=", value, "scholarid");
            return (Criteria) this;
        }

        public Criteria andScholaridLessThan(Integer value) {
            addCriterion("ScholarId <", value, "scholarid");
            return (Criteria) this;
        }

        public Criteria andScholaridLessThanOrEqualTo(Integer value) {
            addCriterion("ScholarId <=", value, "scholarid");
            return (Criteria) this;
        }

        public Criteria andScholaridIn(List<Integer> values) {
            addCriterion("ScholarId in", values, "scholarid");
            return (Criteria) this;
        }

        public Criteria andScholaridNotIn(List<Integer> values) {
            addCriterion("ScholarId not in", values, "scholarid");
            return (Criteria) this;
        }

        public Criteria andScholaridBetween(Integer value1, Integer value2) {
            addCriterion("ScholarId between", value1, value2, "scholarid");
            return (Criteria) this;
        }

        public Criteria andScholaridNotBetween(Integer value1, Integer value2) {
            addCriterion("ScholarId not between", value1, value2, "scholarid");
            return (Criteria) this;
        }

        public Criteria andInstitutionidIsNull() {
            addCriterion("InstitutionId is null");
            return (Criteria) this;
        }

        public Criteria andInstitutionidIsNotNull() {
            addCriterion("InstitutionId is not null");
            return (Criteria) this;
        }

        public Criteria andInstitutionidEqualTo(Integer value) {
            addCriterion("InstitutionId =", value, "institutionid");
            return (Criteria) this;
        }

        public Criteria andInstitutionidNotEqualTo(Integer value) {
            addCriterion("InstitutionId <>", value, "institutionid");
            return (Criteria) this;
        }

        public Criteria andInstitutionidGreaterThan(Integer value) {
            addCriterion("InstitutionId >", value, "institutionid");
            return (Criteria) this;
        }

        public Criteria andInstitutionidGreaterThanOrEqualTo(Integer value) {
            addCriterion("InstitutionId >=", value, "institutionid");
            return (Criteria) this;
        }

        public Criteria andInstitutionidLessThan(Integer value) {
            addCriterion("InstitutionId <", value, "institutionid");
            return (Criteria) this;
        }

        public Criteria andInstitutionidLessThanOrEqualTo(Integer value) {
            addCriterion("InstitutionId <=", value, "institutionid");
            return (Criteria) this;
        }

        public Criteria andInstitutionidIn(List<Integer> values) {
            addCriterion("InstitutionId in", values, "institutionid");
            return (Criteria) this;
        }

        public Criteria andInstitutionidNotIn(List<Integer> values) {
            addCriterion("InstitutionId not in", values, "institutionid");
            return (Criteria) this;
        }

        public Criteria andInstitutionidBetween(Integer value1, Integer value2) {
            addCriterion("InstitutionId between", value1, value2, "institutionid");
            return (Criteria) this;
        }

        public Criteria andInstitutionidNotBetween(Integer value1, Integer value2) {
            addCriterion("InstitutionId not between", value1, value2, "institutionid");
            return (Criteria) this;
        }

        public Criteria andEnglishnameIsNull() {
            addCriterion("EnglishName is null");
            return (Criteria) this;
        }

        public Criteria andEnglishnameIsNotNull() {
            addCriterion("EnglishName is not null");
            return (Criteria) this;
        }

        public Criteria andEnglishnameEqualTo(String value) {
            addCriterion("EnglishName =", value, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameNotEqualTo(String value) {
            addCriterion("EnglishName <>", value, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameGreaterThan(String value) {
            addCriterion("EnglishName >", value, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameGreaterThanOrEqualTo(String value) {
            addCriterion("EnglishName >=", value, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameLessThan(String value) {
            addCriterion("EnglishName <", value, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameLessThanOrEqualTo(String value) {
            addCriterion("EnglishName <=", value, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameLike(String value) {
            addCriterion("EnglishName like", value, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameNotLike(String value) {
            addCriterion("EnglishName not like", value, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameIn(List<String> values) {
            addCriterion("EnglishName in", values, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameNotIn(List<String> values) {
            addCriterion("EnglishName not in", values, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameBetween(String value1, String value2) {
            addCriterion("EnglishName between", value1, value2, "englishname");
            return (Criteria) this;
        }

        public Criteria andEnglishnameNotBetween(String value1, String value2) {
            addCriterion("EnglishName not between", value1, value2, "englishname");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("Name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("Name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("Name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("Name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("Name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("Name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("Name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("Name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("Name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("Name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("Name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("Name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("Name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("Name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("Title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("Title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("Title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("Title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("Title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("Title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("Title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("Title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("Title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("Title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("Title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("Title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("Title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("Title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andOrganizationIsNull() {
            addCriterion("Organization is null");
            return (Criteria) this;
        }

        public Criteria andOrganizationIsNotNull() {
            addCriterion("Organization is not null");
            return (Criteria) this;
        }

        public Criteria andOrganizationEqualTo(String value) {
            addCriterion("Organization =", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationNotEqualTo(String value) {
            addCriterion("Organization <>", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationGreaterThan(String value) {
            addCriterion("Organization >", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationGreaterThanOrEqualTo(String value) {
            addCriterion("Organization >=", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationLessThan(String value) {
            addCriterion("Organization <", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationLessThanOrEqualTo(String value) {
            addCriterion("Organization <=", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationLike(String value) {
            addCriterion("Organization like", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationNotLike(String value) {
            addCriterion("Organization not like", value, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationIn(List<String> values) {
            addCriterion("Organization in", values, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationNotIn(List<String> values) {
            addCriterion("Organization not in", values, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationBetween(String value1, String value2) {
            addCriterion("Organization between", value1, value2, "organization");
            return (Criteria) this;
        }

        public Criteria andOrganizationNotBetween(String value1, String value2) {
            addCriterion("Organization not between", value1, value2, "organization");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("Email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("Email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("Email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("Email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("Email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("Email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("Email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("Email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("Email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("Email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("Email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("Email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("Email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("Email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("Phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("Phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("Phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("Phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("Phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("Phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("Phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("Phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("Phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("Phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("Phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("Phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("Phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("Phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andFansIsNull() {
            addCriterion("Fans is null");
            return (Criteria) this;
        }

        public Criteria andFansIsNotNull() {
            addCriterion("Fans is not null");
            return (Criteria) this;
        }

        public Criteria andFansEqualTo(Integer value) {
            addCriterion("Fans =", value, "fans");
            return (Criteria) this;
        }

        public Criteria andFansNotEqualTo(Integer value) {
            addCriterion("Fans <>", value, "fans");
            return (Criteria) this;
        }

        public Criteria andFansGreaterThan(Integer value) {
            addCriterion("Fans >", value, "fans");
            return (Criteria) this;
        }

        public Criteria andFansGreaterThanOrEqualTo(Integer value) {
            addCriterion("Fans >=", value, "fans");
            return (Criteria) this;
        }

        public Criteria andFansLessThan(Integer value) {
            addCriterion("Fans <", value, "fans");
            return (Criteria) this;
        }

        public Criteria andFansLessThanOrEqualTo(Integer value) {
            addCriterion("Fans <=", value, "fans");
            return (Criteria) this;
        }

        public Criteria andFansIn(List<Integer> values) {
            addCriterion("Fans in", values, "fans");
            return (Criteria) this;
        }

        public Criteria andFansNotIn(List<Integer> values) {
            addCriterion("Fans not in", values, "fans");
            return (Criteria) this;
        }

        public Criteria andFansBetween(Integer value1, Integer value2) {
            addCriterion("Fans between", value1, value2, "fans");
            return (Criteria) this;
        }

        public Criteria andFansNotBetween(Integer value1, Integer value2) {
            addCriterion("Fans not between", value1, value2, "fans");
            return (Criteria) this;
        }

        public Criteria andPersonalpageIsNull() {
            addCriterion("PersonalPage is null");
            return (Criteria) this;
        }

        public Criteria andPersonalpageIsNotNull() {
            addCriterion("PersonalPage is not null");
            return (Criteria) this;
        }

        public Criteria andPersonalpageEqualTo(String value) {
            addCriterion("PersonalPage =", value, "personalpage");
            return (Criteria) this;
        }

        public Criteria andPersonalpageNotEqualTo(String value) {
            addCriterion("PersonalPage <>", value, "personalpage");
            return (Criteria) this;
        }

        public Criteria andPersonalpageGreaterThan(String value) {
            addCriterion("PersonalPage >", value, "personalpage");
            return (Criteria) this;
        }

        public Criteria andPersonalpageGreaterThanOrEqualTo(String value) {
            addCriterion("PersonalPage >=", value, "personalpage");
            return (Criteria) this;
        }

        public Criteria andPersonalpageLessThan(String value) {
            addCriterion("PersonalPage <", value, "personalpage");
            return (Criteria) this;
        }

        public Criteria andPersonalpageLessThanOrEqualTo(String value) {
            addCriterion("PersonalPage <=", value, "personalpage");
            return (Criteria) this;
        }

        public Criteria andPersonalpageLike(String value) {
            addCriterion("PersonalPage like", value, "personalpage");
            return (Criteria) this;
        }

        public Criteria andPersonalpageNotLike(String value) {
            addCriterion("PersonalPage not like", value, "personalpage");
            return (Criteria) this;
        }

        public Criteria andPersonalpageIn(List<String> values) {
            addCriterion("PersonalPage in", values, "personalpage");
            return (Criteria) this;
        }

        public Criteria andPersonalpageNotIn(List<String> values) {
            addCriterion("PersonalPage not in", values, "personalpage");
            return (Criteria) this;
        }

        public Criteria andPersonalpageBetween(String value1, String value2) {
            addCriterion("PersonalPage between", value1, value2, "personalpage");
            return (Criteria) this;
        }

        public Criteria andPersonalpageNotBetween(String value1, String value2) {
            addCriterion("PersonalPage not between", value1, value2, "personalpage");
            return (Criteria) this;
        }

        public Criteria andIntroductionIsNull() {
            addCriterion("Introduction is null");
            return (Criteria) this;
        }

        public Criteria andIntroductionIsNotNull() {
            addCriterion("Introduction is not null");
            return (Criteria) this;
        }

        public Criteria andIntroductionEqualTo(String value) {
            addCriterion("Introduction =", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotEqualTo(String value) {
            addCriterion("Introduction <>", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionGreaterThan(String value) {
            addCriterion("Introduction >", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionGreaterThanOrEqualTo(String value) {
            addCriterion("Introduction >=", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLessThan(String value) {
            addCriterion("Introduction <", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLessThanOrEqualTo(String value) {
            addCriterion("Introduction <=", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLike(String value) {
            addCriterion("Introduction like", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotLike(String value) {
            addCriterion("Introduction not like", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionIn(List<String> values) {
            addCriterion("Introduction in", values, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotIn(List<String> values) {
            addCriterion("Introduction not in", values, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionBetween(String value1, String value2) {
            addCriterion("Introduction between", value1, value2, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotBetween(String value1, String value2) {
            addCriterion("Introduction not between", value1, value2, "introduction");
            return (Criteria) this;
        }

        public Criteria andPapersIsNull() {
            addCriterion("Papers is null");
            return (Criteria) this;
        }

        public Criteria andPapersIsNotNull() {
            addCriterion("Papers is not null");
            return (Criteria) this;
        }

        public Criteria andPapersEqualTo(Integer value) {
            addCriterion("Papers =", value, "papers");
            return (Criteria) this;
        }

        public Criteria andPapersNotEqualTo(Integer value) {
            addCriterion("Papers <>", value, "papers");
            return (Criteria) this;
        }

        public Criteria andPapersGreaterThan(Integer value) {
            addCriterion("Papers >", value, "papers");
            return (Criteria) this;
        }

        public Criteria andPapersGreaterThanOrEqualTo(Integer value) {
            addCriterion("Papers >=", value, "papers");
            return (Criteria) this;
        }

        public Criteria andPapersLessThan(Integer value) {
            addCriterion("Papers <", value, "papers");
            return (Criteria) this;
        }

        public Criteria andPapersLessThanOrEqualTo(Integer value) {
            addCriterion("Papers <=", value, "papers");
            return (Criteria) this;
        }

        public Criteria andPapersIn(List<Integer> values) {
            addCriterion("Papers in", values, "papers");
            return (Criteria) this;
        }

        public Criteria andPapersNotIn(List<Integer> values) {
            addCriterion("Papers not in", values, "papers");
            return (Criteria) this;
        }

        public Criteria andPapersBetween(Integer value1, Integer value2) {
            addCriterion("Papers between", value1, value2, "papers");
            return (Criteria) this;
        }

        public Criteria andPapersNotBetween(Integer value1, Integer value2) {
            addCriterion("Papers not between", value1, value2, "papers");
            return (Criteria) this;
        }

        public Criteria andCitationsIsNull() {
            addCriterion("Citations is null");
            return (Criteria) this;
        }

        public Criteria andCitationsIsNotNull() {
            addCriterion("Citations is not null");
            return (Criteria) this;
        }

        public Criteria andCitationsEqualTo(Integer value) {
            addCriterion("Citations =", value, "citations");
            return (Criteria) this;
        }

        public Criteria andCitationsNotEqualTo(Integer value) {
            addCriterion("Citations <>", value, "citations");
            return (Criteria) this;
        }

        public Criteria andCitationsGreaterThan(Integer value) {
            addCriterion("Citations >", value, "citations");
            return (Criteria) this;
        }

        public Criteria andCitationsGreaterThanOrEqualTo(Integer value) {
            addCriterion("Citations >=", value, "citations");
            return (Criteria) this;
        }

        public Criteria andCitationsLessThan(Integer value) {
            addCriterion("Citations <", value, "citations");
            return (Criteria) this;
        }

        public Criteria andCitationsLessThanOrEqualTo(Integer value) {
            addCriterion("Citations <=", value, "citations");
            return (Criteria) this;
        }

        public Criteria andCitationsIn(List<Integer> values) {
            addCriterion("Citations in", values, "citations");
            return (Criteria) this;
        }

        public Criteria andCitationsNotIn(List<Integer> values) {
            addCriterion("Citations not in", values, "citations");
            return (Criteria) this;
        }

        public Criteria andCitationsBetween(Integer value1, Integer value2) {
            addCriterion("Citations between", value1, value2, "citations");
            return (Criteria) this;
        }

        public Criteria andCitationsNotBetween(Integer value1, Integer value2) {
            addCriterion("Citations not between", value1, value2, "citations");
            return (Criteria) this;
        }

        public Criteria andHindexIsNull() {
            addCriterion("HIndex is null");
            return (Criteria) this;
        }

        public Criteria andHindexIsNotNull() {
            addCriterion("HIndex is not null");
            return (Criteria) this;
        }

        public Criteria andHindexEqualTo(Integer value) {
            addCriterion("HIndex =", value, "hindex");
            return (Criteria) this;
        }

        public Criteria andHindexNotEqualTo(Integer value) {
            addCriterion("HIndex <>", value, "hindex");
            return (Criteria) this;
        }

        public Criteria andHindexGreaterThan(Integer value) {
            addCriterion("HIndex >", value, "hindex");
            return (Criteria) this;
        }

        public Criteria andHindexGreaterThanOrEqualTo(Integer value) {
            addCriterion("HIndex >=", value, "hindex");
            return (Criteria) this;
        }

        public Criteria andHindexLessThan(Integer value) {
            addCriterion("HIndex <", value, "hindex");
            return (Criteria) this;
        }

        public Criteria andHindexLessThanOrEqualTo(Integer value) {
            addCriterion("HIndex <=", value, "hindex");
            return (Criteria) this;
        }

        public Criteria andHindexIn(List<Integer> values) {
            addCriterion("HIndex in", values, "hindex");
            return (Criteria) this;
        }

        public Criteria andHindexNotIn(List<Integer> values) {
            addCriterion("HIndex not in", values, "hindex");
            return (Criteria) this;
        }

        public Criteria andHindexBetween(Integer value1, Integer value2) {
            addCriterion("HIndex between", value1, value2, "hindex");
            return (Criteria) this;
        }

        public Criteria andHindexNotBetween(Integer value1, Integer value2) {
            addCriterion("HIndex not between", value1, value2, "hindex");
            return (Criteria) this;
        }

        public Criteria andGindexIsNull() {
            addCriterion("GIndex is null");
            return (Criteria) this;
        }

        public Criteria andGindexIsNotNull() {
            addCriterion("GIndex is not null");
            return (Criteria) this;
        }

        public Criteria andGindexEqualTo(Integer value) {
            addCriterion("GIndex =", value, "gindex");
            return (Criteria) this;
        }

        public Criteria andGindexNotEqualTo(Integer value) {
            addCriterion("GIndex <>", value, "gindex");
            return (Criteria) this;
        }

        public Criteria andGindexGreaterThan(Integer value) {
            addCriterion("GIndex >", value, "gindex");
            return (Criteria) this;
        }

        public Criteria andGindexGreaterThanOrEqualTo(Integer value) {
            addCriterion("GIndex >=", value, "gindex");
            return (Criteria) this;
        }

        public Criteria andGindexLessThan(Integer value) {
            addCriterion("GIndex <", value, "gindex");
            return (Criteria) this;
        }

        public Criteria andGindexLessThanOrEqualTo(Integer value) {
            addCriterion("GIndex <=", value, "gindex");
            return (Criteria) this;
        }

        public Criteria andGindexIn(List<Integer> values) {
            addCriterion("GIndex in", values, "gindex");
            return (Criteria) this;
        }

        public Criteria andGindexNotIn(List<Integer> values) {
            addCriterion("GIndex not in", values, "gindex");
            return (Criteria) this;
        }

        public Criteria andGindexBetween(Integer value1, Integer value2) {
            addCriterion("GIndex between", value1, value2, "gindex");
            return (Criteria) this;
        }

        public Criteria andGindexNotBetween(Integer value1, Integer value2) {
            addCriterion("GIndex not between", value1, value2, "gindex");
            return (Criteria) this;
        }

        public Criteria andSociabilityIsNull() {
            addCriterion("Sociability is null");
            return (Criteria) this;
        }

        public Criteria andSociabilityIsNotNull() {
            addCriterion("Sociability is not null");
            return (Criteria) this;
        }

        public Criteria andSociabilityEqualTo(Integer value) {
            addCriterion("Sociability =", value, "sociability");
            return (Criteria) this;
        }

        public Criteria andSociabilityNotEqualTo(Integer value) {
            addCriterion("Sociability <>", value, "sociability");
            return (Criteria) this;
        }

        public Criteria andSociabilityGreaterThan(Integer value) {
            addCriterion("Sociability >", value, "sociability");
            return (Criteria) this;
        }

        public Criteria andSociabilityGreaterThanOrEqualTo(Integer value) {
            addCriterion("Sociability >=", value, "sociability");
            return (Criteria) this;
        }

        public Criteria andSociabilityLessThan(Integer value) {
            addCriterion("Sociability <", value, "sociability");
            return (Criteria) this;
        }

        public Criteria andSociabilityLessThanOrEqualTo(Integer value) {
            addCriterion("Sociability <=", value, "sociability");
            return (Criteria) this;
        }

        public Criteria andSociabilityIn(List<Integer> values) {
            addCriterion("Sociability in", values, "sociability");
            return (Criteria) this;
        }

        public Criteria andSociabilityNotIn(List<Integer> values) {
            addCriterion("Sociability not in", values, "sociability");
            return (Criteria) this;
        }

        public Criteria andSociabilityBetween(Integer value1, Integer value2) {
            addCriterion("Sociability between", value1, value2, "sociability");
            return (Criteria) this;
        }

        public Criteria andSociabilityNotBetween(Integer value1, Integer value2) {
            addCriterion("Sociability not between", value1, value2, "sociability");
            return (Criteria) this;
        }

        public Criteria andDiversityIsNull() {
            addCriterion("Diversity is null");
            return (Criteria) this;
        }

        public Criteria andDiversityIsNotNull() {
            addCriterion("Diversity is not null");
            return (Criteria) this;
        }

        public Criteria andDiversityEqualTo(Integer value) {
            addCriterion("Diversity =", value, "diversity");
            return (Criteria) this;
        }

        public Criteria andDiversityNotEqualTo(Integer value) {
            addCriterion("Diversity <>", value, "diversity");
            return (Criteria) this;
        }

        public Criteria andDiversityGreaterThan(Integer value) {
            addCriterion("Diversity >", value, "diversity");
            return (Criteria) this;
        }

        public Criteria andDiversityGreaterThanOrEqualTo(Integer value) {
            addCriterion("Diversity >=", value, "diversity");
            return (Criteria) this;
        }

        public Criteria andDiversityLessThan(Integer value) {
            addCriterion("Diversity <", value, "diversity");
            return (Criteria) this;
        }

        public Criteria andDiversityLessThanOrEqualTo(Integer value) {
            addCriterion("Diversity <=", value, "diversity");
            return (Criteria) this;
        }

        public Criteria andDiversityIn(List<Integer> values) {
            addCriterion("Diversity in", values, "diversity");
            return (Criteria) this;
        }

        public Criteria andDiversityNotIn(List<Integer> values) {
            addCriterion("Diversity not in", values, "diversity");
            return (Criteria) this;
        }

        public Criteria andDiversityBetween(Integer value1, Integer value2) {
            addCriterion("Diversity between", value1, value2, "diversity");
            return (Criteria) this;
        }

        public Criteria andDiversityNotBetween(Integer value1, Integer value2) {
            addCriterion("Diversity not between", value1, value2, "diversity");
            return (Criteria) this;
        }

        public Criteria andActivityIsNull() {
            addCriterion("Activity is null");
            return (Criteria) this;
        }

        public Criteria andActivityIsNotNull() {
            addCriterion("Activity is not null");
            return (Criteria) this;
        }

        public Criteria andActivityEqualTo(Integer value) {
            addCriterion("Activity =", value, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityNotEqualTo(Integer value) {
            addCriterion("Activity <>", value, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityGreaterThan(Integer value) {
            addCriterion("Activity >", value, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityGreaterThanOrEqualTo(Integer value) {
            addCriterion("Activity >=", value, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityLessThan(Integer value) {
            addCriterion("Activity <", value, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityLessThanOrEqualTo(Integer value) {
            addCriterion("Activity <=", value, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityIn(List<Integer> values) {
            addCriterion("Activity in", values, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityNotIn(List<Integer> values) {
            addCriterion("Activity not in", values, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityBetween(Integer value1, Integer value2) {
            addCriterion("Activity between", value1, value2, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityNotBetween(Integer value1, Integer value2) {
            addCriterion("Activity not between", value1, value2, "activity");
            return (Criteria) this;
        }

        public Criteria andAvatarurlIsNull() {
            addCriterion("AvatarUrl is null");
            return (Criteria) this;
        }

        public Criteria andAvatarurlIsNotNull() {
            addCriterion("AvatarUrl is not null");
            return (Criteria) this;
        }

        public Criteria andAvatarurlEqualTo(String value) {
            addCriterion("AvatarUrl =", value, "avatarurl");
            return (Criteria) this;
        }

        public Criteria andAvatarurlNotEqualTo(String value) {
            addCriterion("AvatarUrl <>", value, "avatarurl");
            return (Criteria) this;
        }

        public Criteria andAvatarurlGreaterThan(String value) {
            addCriterion("AvatarUrl >", value, "avatarurl");
            return (Criteria) this;
        }

        public Criteria andAvatarurlGreaterThanOrEqualTo(String value) {
            addCriterion("AvatarUrl >=", value, "avatarurl");
            return (Criteria) this;
        }

        public Criteria andAvatarurlLessThan(String value) {
            addCriterion("AvatarUrl <", value, "avatarurl");
            return (Criteria) this;
        }

        public Criteria andAvatarurlLessThanOrEqualTo(String value) {
            addCriterion("AvatarUrl <=", value, "avatarurl");
            return (Criteria) this;
        }

        public Criteria andAvatarurlLike(String value) {
            addCriterion("AvatarUrl like", value, "avatarurl");
            return (Criteria) this;
        }

        public Criteria andAvatarurlNotLike(String value) {
            addCriterion("AvatarUrl not like", value, "avatarurl");
            return (Criteria) this;
        }

        public Criteria andAvatarurlIn(List<String> values) {
            addCriterion("AvatarUrl in", values, "avatarurl");
            return (Criteria) this;
        }

        public Criteria andAvatarurlNotIn(List<String> values) {
            addCriterion("AvatarUrl not in", values, "avatarurl");
            return (Criteria) this;
        }

        public Criteria andAvatarurlBetween(String value1, String value2) {
            addCriterion("AvatarUrl between", value1, value2, "avatarurl");
            return (Criteria) this;
        }

        public Criteria andAvatarurlNotBetween(String value1, String value2) {
            addCriterion("AvatarUrl not between", value1, value2, "avatarurl");
            return (Criteria) this;
        }

        public Criteria andLastknowntimeIsNull() {
            addCriterion("LastKnownTime is null");
            return (Criteria) this;
        }

        public Criteria andLastknowntimeIsNotNull() {
            addCriterion("LastKnownTime is not null");
            return (Criteria) this;
        }

        public Criteria andLastknowntimeEqualTo(Date value) {
            addCriterion("LastKnownTime =", value, "lastknowntime");
            return (Criteria) this;
        }

        public Criteria andLastknowntimeNotEqualTo(Date value) {
            addCriterion("LastKnownTime <>", value, "lastknowntime");
            return (Criteria) this;
        }

        public Criteria andLastknowntimeGreaterThan(Date value) {
            addCriterion("LastKnownTime >", value, "lastknowntime");
            return (Criteria) this;
        }

        public Criteria andLastknowntimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LastKnownTime >=", value, "lastknowntime");
            return (Criteria) this;
        }

        public Criteria andLastknowntimeLessThan(Date value) {
            addCriterion("LastKnownTime <", value, "lastknowntime");
            return (Criteria) this;
        }

        public Criteria andLastknowntimeLessThanOrEqualTo(Date value) {
            addCriterion("LastKnownTime <=", value, "lastknowntime");
            return (Criteria) this;
        }

        public Criteria andLastknowntimeIn(List<Date> values) {
            addCriterion("LastKnownTime in", values, "lastknowntime");
            return (Criteria) this;
        }

        public Criteria andLastknowntimeNotIn(List<Date> values) {
            addCriterion("LastKnownTime not in", values, "lastknowntime");
            return (Criteria) this;
        }

        public Criteria andLastknowntimeBetween(Date value1, Date value2) {
            addCriterion("LastKnownTime between", value1, value2, "lastknowntime");
            return (Criteria) this;
        }

        public Criteria andLastknowntimeNotBetween(Date value1, Date value2) {
            addCriterion("LastKnownTime not between", value1, value2, "lastknowntime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Scholar
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Scholar
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}