package cn.edu.buaa.scholarshipserver.models;

import java.io.Serializable;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.UserID
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.Password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.Name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.Sex
     *
     * @mbggenerated
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.UserImagePath
     *
     * @mbggenerated
     */
    private String userimagepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.Organization
     *
     * @mbggenerated
     */
    private String organization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.Email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.BriefIntroduction
     *
     * @mbggenerated
     */
    private String briefintroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.Identify
     *
     * @mbggenerated
     */
    private Integer identify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table User
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.UserID
     *
     * @return the value of User.UserID
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.UserID
     *
     * @param userid the value for User.UserID
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.Password
     *
     * @return the value of User.Password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.Password
     *
     * @param password the value for User.Password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.Name
     *
     * @return the value of User.Name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.Name
     *
     * @param name the value for User.Name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.Sex
     *
     * @return the value of User.Sex
     *
     * @mbggenerated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.Sex
     *
     * @param sex the value for User.Sex
     *
     * @mbggenerated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.UserImagePath
     *
     * @return the value of User.UserImagePath
     *
     * @mbggenerated
     */
    public String getUserimagepath() {
        return userimagepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.UserImagePath
     *
     * @param userimagepath the value for User.UserImagePath
     *
     * @mbggenerated
     */
    public void setUserimagepath(String userimagepath) {
        this.userimagepath = userimagepath == null ? null : userimagepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.Organization
     *
     * @return the value of User.Organization
     *
     * @mbggenerated
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.Organization
     *
     * @param organization the value for User.Organization
     *
     * @mbggenerated
     */
    public void setOrganization(String organization) {
        this.organization = organization == null ? null : organization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.Email
     *
     * @return the value of User.Email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.Email
     *
     * @param email the value for User.Email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.BriefIntroduction
     *
     * @return the value of User.BriefIntroduction
     *
     * @mbggenerated
     */
    public String getBriefintroduction() {
        return briefintroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.BriefIntroduction
     *
     * @param briefintroduction the value for User.BriefIntroduction
     *
     * @mbggenerated
     */
    public void setBriefintroduction(String briefintroduction) {
        this.briefintroduction = briefintroduction == null ? null : briefintroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.Identify
     *
     * @return the value of User.Identify
     *
     * @mbggenerated
     */
    public Integer getIdentify() {
        return identify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.Identify
     *
     * @param identify the value for User.Identify
     *
     * @mbggenerated
     */
    public void setIdentify(Integer identify) {
        this.identify = identify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userid=").append(userid);
        sb.append(", password=").append(password);
        sb.append(", name=").append(name);
        sb.append(", sex=").append(sex);
        sb.append(", userimagepath=").append(userimagepath);
        sb.append(", organization=").append(organization);
        sb.append(", email=").append(email);
        sb.append(", briefintroduction=").append(briefintroduction);
        sb.append(", identify=").append(identify);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}