package cn.edu.buaa.scholarshipserver.models;

import java.util.ArrayList;
import java.util.List;

public class WriterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Writer
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Writer
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Writer
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Writer
     *
     * @mbggenerated
     */
    public WriterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Writer
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Writer
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Writer
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Writer
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Writer
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Writer
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Writer
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Writer
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Writer
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Writer
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Writer
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPaperidIsNull() {
            addCriterion("PaperId is null");
            return (Criteria) this;
        }

        public Criteria andPaperidIsNotNull() {
            addCriterion("PaperId is not null");
            return (Criteria) this;
        }

        public Criteria andPaperidEqualTo(Long value) {
            addCriterion("PaperId =", value, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidNotEqualTo(Long value) {
            addCriterion("PaperId <>", value, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidGreaterThan(Long value) {
            addCriterion("PaperId >", value, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidGreaterThanOrEqualTo(Long value) {
            addCriterion("PaperId >=", value, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidLessThan(Long value) {
            addCriterion("PaperId <", value, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidLessThanOrEqualTo(Long value) {
            addCriterion("PaperId <=", value, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidIn(List<Long> values) {
            addCriterion("PaperId in", values, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidNotIn(List<Long> values) {
            addCriterion("PaperId not in", values, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidBetween(Long value1, Long value2) {
            addCriterion("PaperId between", value1, value2, "paperid");
            return (Criteria) this;
        }

        public Criteria andPaperidNotBetween(Long value1, Long value2) {
            addCriterion("PaperId not between", value1, value2, "paperid");
            return (Criteria) this;
        }

        public Criteria andScholaridIsNull() {
            addCriterion("ScholarId is null");
            return (Criteria) this;
        }

        public Criteria andScholaridIsNotNull() {
            addCriterion("ScholarId is not null");
            return (Criteria) this;
        }

        public Criteria andScholaridEqualTo(Integer value) {
            addCriterion("ScholarId =", value, "scholarid");
            return (Criteria) this;
        }

        public Criteria andScholaridNotEqualTo(Integer value) {
            addCriterion("ScholarId <>", value, "scholarid");
            return (Criteria) this;
        }

        public Criteria andScholaridGreaterThan(Integer value) {
            addCriterion("ScholarId >", value, "scholarid");
            return (Criteria) this;
        }

        public Criteria andScholaridGreaterThanOrEqualTo(Integer value) {
            addCriterion("ScholarId >=", value, "scholarid");
            return (Criteria) this;
        }

        public Criteria andScholaridLessThan(Integer value) {
            addCriterion("ScholarId <", value, "scholarid");
            return (Criteria) this;
        }

        public Criteria andScholaridLessThanOrEqualTo(Integer value) {
            addCriterion("ScholarId <=", value, "scholarid");
            return (Criteria) this;
        }

        public Criteria andScholaridIn(List<Integer> values) {
            addCriterion("ScholarId in", values, "scholarid");
            return (Criteria) this;
        }

        public Criteria andScholaridNotIn(List<Integer> values) {
            addCriterion("ScholarId not in", values, "scholarid");
            return (Criteria) this;
        }

        public Criteria andScholaridBetween(Integer value1, Integer value2) {
            addCriterion("ScholarId between", value1, value2, "scholarid");
            return (Criteria) this;
        }

        public Criteria andScholaridNotBetween(Integer value1, Integer value2) {
            addCriterion("ScholarId not between", value1, value2, "scholarid");
            return (Criteria) this;
        }

        public Criteria andAuthorsequenceIsNull() {
            addCriterion("AuthorSequence is null");
            return (Criteria) this;
        }

        public Criteria andAuthorsequenceIsNotNull() {
            addCriterion("AuthorSequence is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorsequenceEqualTo(Integer value) {
            addCriterion("AuthorSequence =", value, "authorsequence");
            return (Criteria) this;
        }

        public Criteria andAuthorsequenceNotEqualTo(Integer value) {
            addCriterion("AuthorSequence <>", value, "authorsequence");
            return (Criteria) this;
        }

        public Criteria andAuthorsequenceGreaterThan(Integer value) {
            addCriterion("AuthorSequence >", value, "authorsequence");
            return (Criteria) this;
        }

        public Criteria andAuthorsequenceGreaterThanOrEqualTo(Integer value) {
            addCriterion("AuthorSequence >=", value, "authorsequence");
            return (Criteria) this;
        }

        public Criteria andAuthorsequenceLessThan(Integer value) {
            addCriterion("AuthorSequence <", value, "authorsequence");
            return (Criteria) this;
        }

        public Criteria andAuthorsequenceLessThanOrEqualTo(Integer value) {
            addCriterion("AuthorSequence <=", value, "authorsequence");
            return (Criteria) this;
        }

        public Criteria andAuthorsequenceIn(List<Integer> values) {
            addCriterion("AuthorSequence in", values, "authorsequence");
            return (Criteria) this;
        }

        public Criteria andAuthorsequenceNotIn(List<Integer> values) {
            addCriterion("AuthorSequence not in", values, "authorsequence");
            return (Criteria) this;
        }

        public Criteria andAuthorsequenceBetween(Integer value1, Integer value2) {
            addCriterion("AuthorSequence between", value1, value2, "authorsequence");
            return (Criteria) this;
        }

        public Criteria andAuthorsequenceNotBetween(Integer value1, Integer value2) {
            addCriterion("AuthorSequence not between", value1, value2, "authorsequence");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Writer
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Writer
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}