package cn.edu.buaa.scholarshipserver.models;

import java.io.Serializable;

public class Writer extends WriterKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Writer.AuthorSequence
     *
     * @mbggenerated
     */
    private Integer authorsequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Writer
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Writer.AuthorSequence
     *
     * @return the value of Writer.AuthorSequence
     *
     * @mbggenerated
     */
    public Integer getAuthorsequence() {
        return authorsequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Writer.AuthorSequence
     *
     * @param authorsequence the value for Writer.AuthorSequence
     *
     * @mbggenerated
     */
    public void setAuthorsequence(Integer authorsequence) {
        this.authorsequence = authorsequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Writer
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", authorsequence=").append(authorsequence);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}