package cn.edu.buaa.scholarshipserver.models;

import java.io.Serializable;

public class WriterKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Writer.PaperId
     *
     * @mbggenerated
     */
    private Long paperid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Writer.ScholarId
     *
     * @mbggenerated
     */
    private Integer scholarid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Writer
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Writer.PaperId
     *
     * @return the value of Writer.PaperId
     *
     * @mbggenerated
     */
    public Long getPaperid() {
        return paperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Writer.PaperId
     *
     * @param paperid the value for Writer.PaperId
     *
     * @mbggenerated
     */
    public void setPaperid(Long paperid) {
        this.paperid = paperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Writer.ScholarId
     *
     * @return the value of Writer.ScholarId
     *
     * @mbggenerated
     */
    public Integer getScholarid() {
        return scholarid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Writer.ScholarId
     *
     * @param scholarid the value for Writer.ScholarId
     *
     * @mbggenerated
     */
    public void setScholarid(Integer scholarid) {
        this.scholarid = scholarid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Writer
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", paperid=").append(paperid);
        sb.append(", scholarid=").append(scholarid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}